### PR TITLE
feat: Adding the ballot form configuration feature

### PR DESCRIPTION
**Pull request by make-sundae**
Working functions

    rearrange
    Add
    update
    delete
    
    will work on styles and modal pa
    
    https://drive.google.com/file/d/1Ir61vMKP_Wx238jMobWW8W93JzBHKlZk/view?usp=sharing
    
```
    CREATE TABLE `vote_guidelines` (
  `guideline_id` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `seq` MEDIUMINT(8) UNSIGNED NOT NULL,
  `description` TEXT NOT NULL,
  PRIMARY KEY (`guideline_id`)
);
```

### CODE REVIEW

**Review by Carl-Tabuso — COMMENTED** [review]
Issues found:
- Can click the **Add Rule** button despite the textarea being empty
- Textarea allows for leading and trailing whitespaces
- Too many buttons — Edit is unnecessary

image

- Misleading button colors — I thought the button state was disabled but on click, it deleted the rule

image

> [!NOTE]
> Try to make the fonts smaller. Some of them, especially on Voting Guidelines and Positions, felt unnecessary large.

I don't think it's possible to have the voting guidelines reflected on the ballot form, no?

> [!TIP]
> You can add a feedback/message every time a new rule is created, like toast or alerts.

Shall we proceed merging? I can tag this as a `need issue ticket` so we can track the issues found in the future?

**Comment by make-sundae** [comment]
> Issues found:
> 
> * Can click the **Add Rule** button despite the text being empty
> * Textarea allows for leading and trailing whitespaces
> * Too many buttons — Edit is unnecessary

currently working on client side

but these validation are enforced on backend plng

> 
> image
> 
> * Misleading button colors — I thought the button state was disabled but on click, it deleted the rule
> 
> image
> 
> Note
> 
> Try to make the fonts smaller. Some of them, especially on Voting Guidelines and Positions, felt unnecessary large.

will adjust those since I made all my fonts size relative to rem units as well as screen size 

> 
> I don't think it's possible to have the voting guidelines reflected on the ballot form, no?

There is I notified the developer this morning about the database structure I used

**Comment by Carl-Tabuso** [comment]
> There is I notified the developer this morning about the database structure I used.

What I meant to say was if it's feasible tonight to reflect the new added rule to the ballot form.

Last. Do i wait for you to finish  before we merge this pr? 
I'm referring to this:
> currently working on client side

**Comment by make-sundae** [comment]
I refined the validation
Refined some styles

Added a little feedback on vote guidelines

I reenable toast on vote schedule validation

if this is okay for now it can be merge
will follow updates on next prs

**Comment by Carl-Tabuso** [comment]
I still encounter the leading whitespaces 

image

Upon testing, the truncation only happens if a single whitespace is followed by a valid character in the beginning. But upon hitting the Add Rule button, the texts were truncated properly. What do you make of this? Do we proceed with the merging?

**Comment by make-sundae** [comment]
I think you can create an issue ticket for tracking of this issue
and proceed to merging thank you

**Review by Carl-Tabuso — APPROVED** [review]
Need Task List

**Pull request merged**
