### PR TITLE
Implementation of Email Input Validation, Sending Modal, and Various Improvements

### LINKED ISSUE #115: Login Page: Forgot Password Send Button State
## Non-Urgent

While the magic happens in the SMTP server sending an email to a user, there is no indicator that the email is actually being sent aside from the disable state of the "Send Email" button. See video below

https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/assets/162773681/029a615f-6b52-45cd-afe4-e8191e353b31

We can make use of a preloader already built in Bootstrap. @biellamariscotes  @Jeremie-Legrama  @bobbymorante what do you think?

### LINKED ISSUE #159: Login Page: Forgot Password Cancel Refresh
### Forgot Password
In reference to the conversation in this [PR](https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/pull/158), an exception in closing (**Cancel** button) the modal when the input field is empty should be implemented.

### PR DESCRIPTION
**Pull request by Carl-Tabuso**
# FEATURES

1. Implemented a modal for sending email.
2. Added additional event listeners to improve email validation to ensure the correct format for login and an existing user check for forgot password form.

### Proof of Testing
https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/assets/162773681/f20a1bfe-53ee-405d-9fb7-8de558581509

# BUG FIXES

1. Resolved an issue where the page would refresh every time the "Cancel" button was clicked on the forgot password modal. The modal now resets properly upon clicking "Cancel" without refreshing the login page. This shall resolve #159 and closes #115

### Proof of Testing
https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/assets/162773681/98a765c1-2c84-4649-ae11-a2328d96bc0d
 

# STYLES

1.  Added a text-white class to the sign-up button for improved visibility and consistency with the other button design.
2. Added CSS properties to resize the sending email GIF to match the `validate-voter` page implementation.

#
**Notes:** Please review the changes and test the new functionalities to ensure everything works as expected.

### CODE REVIEW

**Comment by biellamariscotes** [comment]
The changes to the **Cancel** button has been approved. 

But I ran into some issues with the Sending Email Modal when testing the Forgot Password feature. Below are the details with attached proof of testing for each scenario.

<hr>

While simulating the Forgot Password process, starting from registration, an error occurs when attempting to send the email. This prevents the email/possible error toasts (or modals) from being dispatched successfully. Please refer to the video for a detailed demonstration:

https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/assets/135019439/9953113a-a37a-4e96-b162-da9322ea94df

<hr>

I've also attempted the Forgot Password modal with different **account_status**. All of them have the **role** of `student_voter`. The bugs have also persisted.

###  account_status: for_verfication & verified
Same bug as the first video. The email for account verification is not being sent, and there is an error appearing in the console.

https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/assets/135019439/60385902-e1f7-4e7c-a363-575b9c30565d

<hr>

### account_status: invalid

When an invalid account is used for the Forgot Password functionality, the Forgot Password modal immediately collapses. See here:

https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/assets/135019439/c4222851-23f2-4668-85be-b5d136aff893

<hr>

### With other browser (Google Chrome):


https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/assets/135019439/f744bd75-888a-4eac-9d15-6d92cde777d1

**Comment by Carl-Tabuso** [comment]
> The changes to the **Cancel** button has been approved.
> 
> But I ran into some issues with the Sending Email Modal when testing the Forgot Password feature. Below are the details with attached proof of testing for each scenario.
> 
> While simulating the Forgot Password process, starting from registration, an error occurs when attempting to send the email. This prevents the email/possible error toasts (or modals) from being dispatched successfully. Please refer to the video for a detailed demonstration:
> 
>  bandicam.2024-06-09.19-02-26-136.mp4 
> I've also attempted the Forgot Password modal with different **account_status**. All of them have the **role** of `student_voter`. The bugs have also persisted.
> 
> ### account_status: for_verfication & verified
> Same bug as the first video. The email for account verification is not being sent, and there is an error appearing in the console.
> 
>  bandicam.2024-06-09.18-52-43-455.mp4 
> ### account_status: invalid
> When an invalid account is used for the Forgot Password functionality, the Forgot Password modal immediately collapses. See here:
> 
>  bandicam.2024-06-09.18-48-01-153.mp4 
> ### With other browser (Google Chrome):
>  bandicam.2024-06-09.19-22-45-418.mp4

I have tested it on my end. Strangely, I didn't encounter these issues at all on the page and the console. Further, I've tested it both on Edge and Chrome. Since the description of my pull request has a sample recording of such on Chrome. This is how the forgot password behaves on Edge for **for_verification** and **verified** status. 


https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/assets/162773681/3cc479a5-9e30-4118-bcf1-5c7500f90e00



But for the invalid, that's a good find. I shall do a follow-up commit for the invalid status issue.

**Comment by Carl-Tabuso** [comment]
## CHANGES

### Invalid Account Status

1. 1d776ccc0810e111dbf4fc5d953de4a9a77d1c07 Add account_status on the SQL query used for validation.
2. a3c61d6c68e3a147ecee33e8229d4ef3ab47d237 Add additional check in javascript event listeners to determine if a voter account_status is equals to **invalid**

https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/assets/162773681/0a06cc32-0ccb-47d9-8251-3538fc642d83

**Review by biellamariscotes — APPROVED** [review]
Changes have been approved, will now merge.

**Pull request merged**
