### PR TITLE
feat: AT3-159 added registration schedule configuration page

### PR DESCRIPTION
**Pull request by make-sundae**
Table used

```
CREATE TABLE `registration_schedule` (
  `schedule_id` tinyint(3) UNSIGNED NOT NULL,
  `start` datetime NOT NULL,
  `close` datetime NOT NULL
);
```

### CODE REVIEW

**Comment by Carl-Tabuso** [comment]
I would have to review PR #264 prior to this PR, correct? I think it would automatically close, should this open pr be merged?

**Comment by make-sundae** [comment]
> I would have to review PR #264 prior to this PR, correct? I think it would automatically close, should this open pr be merged?

Yes, the pr 264 first


> I think it would automatically close, should this open pr be merged?

I have no prior idea if it will automatically close 
this pr can be merge 
as I had already created a branch on my local for the creation of faq page

**Comment by make-sundae** [comment]
Up anyone hahahha will be pushing next pr soon for faq config

**Comment by Carl-Tabuso** [comment]
We might have to go over your PR prior to this. I remember that github does actually auto-merged a pr if its commit messages are identical to others. I don't know why is that but maybe it checks the commit hash.

**Comment by Carl-Tabuso** [comment]
This is working on my end. On registration, I will just have to query the registration_schedule table to check whether the schedule is open for a particular org. Is there anything else you want to add? I can approve of this.

**Comment by make-sundae** [comment]
This can be merge if working well thank you

will follow the SQL in PHP later

**Review by Carl-Tabuso — APPROVED** [review]

**Comment by make-sundae** [comment]
here is the [create-reg-schedule.php ](https://drive.google.com/file/d/1EF4cypDQluDBm5C3l1XO1fyxGgqG7sY9/view?usp=sharing)

**Pull request merged**
