### PR TITLE
CAM - Committee Table Search, Sorting, and Pagination has been fixed

### PR DESCRIPTION
**Pull request by LZionDEVQA**
**Overview**
- Search, Sorting, Pagination has been fixed for this module.
- Improvement of the account details page
- Set head admin role as allowed role to access the add admin page.
- Added error-reporting for includes in pages.
- Added filter and delete functionality in manage-committee
- Added Delete and change of role in account details.

**Additional Information**
- UI Responsiveness for mobile is the only left in CAM Module

### CODE REVIEW

**Comment by biellamariscotes** [comment]
<h1> Issues Found </h1>

https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/assets/135019439/8bf676d4-c2e6-41ad-a215-658ddc358cec

- No empty state.
- The table does not render any accounts in the table, despite the existing data in the db.
- Does not include the insertion of the `account_status` column in the form.

The table not loading properly perhaps due to the outdated data structure for the `account_status`, as laid out in your `manage-members.php` It should also not be **For Verification**, and should be labeled as **verified** instead:

image

Could you please provide a simulation/how it appears to you, as well as the contents and structure of your `voter` table?

<h1>Enhancements</h1>

- In `admin-creation.php`, remove the **X mark** from the **Created Modal** since you are using the `setTimeout` function to load it, so the icon is therefore redundant:

```
<div class="d-flex justify-content-end">
      <i class="fa fa-solid fa-circle-xmark fa-xl close-mark light-gray" id="closeModal"></i>
</div>
```

**Comment by LZionDEVQA** [comment]
This is how it looks to me @biellamariscotes  , tried it also in different web browser (mozilla firefox).


https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/assets/164865471/6768b01d-ad6d-4dc1-884c-7165e01c11e6


Also tried adding new account

https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/assets/164865471/a8a0ac91-7353-41e8-82eb-82a77fef036b

**Comment by biellamariscotes** [comment]
Can you share the structure of your `voter` table? And please do the enhancement that I mentioned if you can in this open PR. Also, make sure that your empty state spans the entire div and gets rid of the table header.

**Comment by LZionDEVQA** [comment]
@biellamariscotes this is my voter table
image
image

For the enhancement, will commit it later with the enhancement of the account details page and the changes in allowed roles for creating an admin account that will be set only to head_admin as carl said.

**Comment by LZionDEVQA** [comment]
@biellamariscotes I think the problem is within my search and fetch committee php files. I adjusted it, can you please check it again? Thank you. Also made the enhancement and the requested head_admin role for the add admin and also added the error-reporting.php in [c153f89](https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/pull/169/commits/c153f89f8aef23a0eae64cf51ab61502cd6fc8ee) for the issue #152 


Role is set to admin
https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/assets/164865471/56950470-f168-4876-8313-7f1f6ecb7ca7

Role is set to head admin
https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/assets/164865471/a1a99546-4567-4c88-b057-7c4e30c99e39

**Comment by Carl-Tabuso** [comment]
> https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/assets/164865471/56950470-f168-4876-8313-7f1f6ecb7ca7

Hello, dipping my fingers here. Perhaps we should remove the dropdown options **Add Admin** and **Admin Accounts** altogether—they serve no purpose if an account type is of admin. Instead of a dropdown of **Manage Accounts**, we can maybe make it something like **Manage Voters** without the dropdown option.

**Comment by biellamariscotes** [comment]
Thank you for addressing the issue, it's now working fine.

> Hello, dipping my fingers here. Perhaps we should remove the dropdown options **Add Admin** and **Admin Accounts** altogether—they serve no purpose if an account type is of admin. Instead of a dropdown of **Manage Accounts**, we can maybe make it something like **Manage Voters** without the dropdown option.

I'm in support of this idea. Let's try to incorporate that proposed enhancement into this PR so that the sidebar for the admin roles is configured once this PR has been merged.

I've removed the **bug label** but will retain the **enhancement label** for this reason. @Andrei-Matibag

**Comment by LZionDEVQA** [comment]
Hello, I added a php class file named change-role-class.php under the classes folder since I'm having an error when using the VoterManager in query-handler.php when updating the role. I tried different approach using the VoterManager but it always bring back a 500 error. I had this error in error logs:

_[Fri Jun 21 17:38:55.018468 2024] [php:error] [pid 14456:tid 1872] [client ::1:53240] PHP Fatal error:  Uncaught ArgumentCountError: The number of elements in the type definition string must match the number of bind variables in C:\\xampp\\htdocs\\version_2\\PUPSRC-AutomatedElectionSystem\\src\\includes\\classes\\query-handler.php:20\nStack trace:\n#0_ 

**Major errors when using the VoterManager:**
**PHP Fatal error: Uncaught ArgumentCountError** and **"The number of elements in the type definition string must match the number of bind variables"** 

Instead of changing something in the voter manager that might affect the system, I created a new class file to match the required number of elements in bind_param.

**Comment by LZionDEVQA** [comment]
Can you review the added functionalities? @biellamariscotes thank you. Will surely commit the sidebar enhancement within the remaining hours today. Thank you again.

**Comment by LZionDEVQA** [comment]
@biellamariscotes @Carl-Tabuso Is this correct for the changes in the sidebar? 

My recent commit [aa87956](https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/pull/169/commits/aa879567d45882a1f496aa1e5465f6356a2119b6) solved the issue #175 


https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/assets/164865471/8a57e8f0-5d44-486d-a4fe-50cd3a6dacc0

**Comment by Carl-Tabuso** [comment]
> @biellamariscotes @Carl-Tabuso Is this correct for the changes in the sidebar? My recent commit is this.

Give me until tonight. I'll provide my review on the implementation of role-based sidebar changes. Also, don't forget to mention/close the issue ticket assigned to you regarding this commit:

> https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/pull/169/commits/aa879567d45882a1f496aa1e5465f6356a2119b6 fix: change the role access to sidebar regarding with admin and head admin

**Comment by Carl-Tabuso** [comment]
It works just fine on my end. However for future improvement, I would suggest segregating the javascript for chevron icon dropdown toggle into a separate javascript file for modularization and cleaner code.

Code Block `sidebar.php`

```javascript
<script>
	document.addEventListener("DOMContentLoaded", function () {
		var submenuToggle = document.getElementById("submenuToggle");
		var submenuIcon = document.getElementById("submenuIcon");

		submenuToggle.addEventListener("click", function () {
			if (submenuIcon.classList.contains("fa-chevron-right")) {
				submenuIcon.classList.remove("fa-chevron-right");
				submenuIcon.classList.add("fa-chevron-down");
			} else {
				submenuIcon.classList.remove("fa-chevron-down");
				submenuIcon.classList.add("fa-chevron-right");
			}
			submenuIcon.style.transition = "transform 0.5s ease";
		});
	});
</script>
``` 

This particular code block above is repeated on your dropdown toggle.

image


With that being said, await the review of biella before merge.

**Comment by biellamariscotes** [comment]
The requested changes have been reviewed, and it's working fine. However, there is a critical issue (a bug that can lead to big impact) that I found that needs to be addressed:

- ❗ In the email in **Add Admin**, it still accepts email that still exists in the database of SCO. Please create a validation for this to stop the form from submitting.

- When in viewing the Admin Account, the Mange Users dropdown & Admin Accounts does not have the highlight background:
image

Also, please refactor your code as per @Carl-Tabuso's comment.

**Comment by biellamariscotes** [comment]
Update please. @Andrei-Matibag

**Comment by LZionDEVQA** [comment]
The highlight background in sidebar has been fixed as shown and refactor the code to separate the js file.


https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/assets/164865471/90248ed8-941c-4166-8e6a-0ebfe6724043

**Comment by Carl-Tabuso** [comment]
> The highlight background in sidebar has been fixed as shown and refactor the code to separate the js file.
> 
>  sidebar.fix.mp4

Can you have your breadcrumbs properly aligned with the table. Take the example below taken from Figma

image

**Comment by biellamariscotes** [comment]
When on Account Details page, the dropdown should also be highlighted.

image

Refer to the state of the sidebar of Manage Accounts > Voters' Accounts > Validate Voter page.

Also, if you can, make the "Email already exists" as a modal since the validation is server-side.

**Comment by LZionDEVQA** [comment]
The email exist modal has been added

https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/assets/164865471/93f6c571-4077-4142-ba73-4e6375f0122e

**Comment by LZionDEVQA** [comment]
Admin Accounts is also getting highlighted when on account details page 

image

**Comment by LZionDEVQA** [comment]
Fixed the add committee breadcrumbs size
image

**Review by biellamariscotes — APPROVED** [review]
Changes have been approved. Will now proceed to merging.

**Pull request merged**
