### PR TITLE
Fixed Modal and null value in database

### LINKED ISSUE #287: [ENHANCEMENT]: Duplicate entries on voter importing
- CSV and Excel files can be imported, even if they contain duplicate entries. However, the system will only add unique voter entries to the database. Duplicate entries will be ignored during the import process.
- After the import, a list of ignored duplicate entries will be displayed in a modal.

### PR DESCRIPTION
**Pull request by LZionDEVQA**
**Overview**

- Reduced message for Modal in Import
- I removed the null value in database if there are missing value for non-required row in the file
- Included list of duplicates

**Additional Information**

- It appears that the other modals are not working properly for some validations. (I'll fix it later.)
- I will integrate later the continuation of import process even if there are duplicates

image
image
image

resolve #287

### CODE REVIEW

**Comment by LZionDEVQA** [comment]
I added the hyperlink for the required format

image

resolve #311

**Comment by LZionDEVQA** [comment]
I made it as a modal

**Comment by Carl-Tabuso** [comment]
Once year-level and section have been removed, notify me immediately.

**Comment by LZionDEVQA** [comment]
@Carl-Tabuso I removed the year level and section and restore the null values if it's empty

**Comment by LZionDEVQA** [comment]
image
 This will be the new sample format

**Review by Carl-Tabuso — APPROVED** [review]

**Pull request merged**
