### PR TITLE
chore: adding the activity logging on faq page

### LINKED ISSUE #217: Create FAQ Config

### PR DESCRIPTION
**Pull request by make-sundae**
- accessing the page
- deleting an item
- adding an item
- updating an item

Apologies for pushing for same branch name it happened that I was pushing and it has been merged 1 mins ago

this shall close #217

### CODE REVIEW

**Review by Carl-Tabuso — COMMENTED** [review]
Is it important to log this activity because it feels a little bit trivial and doesn't provide any informative value for both the user and admin? Moreover, it will only clog the activity log page.

```php
define('ACCESS_FAQ', 'access_faq');
// ...code here
ACCESS_FAQ => 'You <strong>accessed</strong> the FAQ configuration.',
```

**Comment by make-sundae** [comment]
Already removed accessing logs

**Comment by Carl-Tabuso** [comment]
I'm encountering an issue on deletion of a faq. It's getting logged as "Update" rather than "Delete." See the video below. I like to point out also the button "Add Rule," do change the label accordingly to the action being made.

https://github.com/user-attachments/assets/1a3bec42-87b8-4fc9-94f8-00f1d5a2a1db

**Comment by make-sundae** [comment]
But I wasnt able to reproduce the update log  bug
https://drive.google.com/file/d/1t5U5AVu0HbfovcIlFMHbTuzNT636V91A/view?usp=sharing

Working on correct button label

**Comment by make-sundae** [comment]
I wasnt able to reproduce the bug even on piie no fix made on activity logging still

**Review by Carl-Tabuso — APPROVED** [review]
For some reason, it's now working.

**Pull request merged**
