### PR TITLE
Fixed search icon and null values in the table

### LINKED ISSUE #315: Manage Admin: Null Values and Search Bar
Place the search icon within the search bar and remove the null values on Full Name column.

image

### PR DESCRIPTION
**Pull request by LZionDEVQA**
**Overview**

-Search Icon is moved inside the search bar
-NULL values from database is prevented from showing to the committee table

**Additional Information**

-I forgot to create a new branch. I apologize

image
image

resolve #315

### CODE REVIEW

**Comment by LZionDEVQA** [comment]
**Overview**

-Instead of checking the main database. It will check the sco db only
-Added double insertion after importing successfully. It will insert in the current db that is being used and the sco database

image
image

**Comment by LZionDEVQA** [comment]
Should I change the import failed modal message?

**Comment by LZionDEVQA** [comment]
What should I put to make it more straightforward?

**Comment by Andrei-Matibag** [comment]
image

**Comment by LZionDEVQA** [comment]
image

**Comment by Carl-Tabuso** [comment]
> image

This'll do

**Review by Carl-Tabuso — APPROVED** [review]

**Pull request merged**
