### PR TITLE
user settings

### PR DESCRIPTION
**Pull request by Andrea-Villalobos**
fix: regression bug in ballot form, display of ballot preview modal, submit vote

> After making adjustment with the long candidate names as per my last pr, the modal was not showing and does not let submit the vote, is now working. Apologies for not double checking.

Proof of Testing:

https://github.com/user-attachments/assets/70476438-3d60-4ddd-a318-21aed8021d36

refactor: AT1-219 ajax form submission in setting new email
> add adjustments in the ui

https://github.com/user-attachments/assets/582d5391-f358-46ee-9239-51470ace9ee4

style: AT1-219 minor ui adjustments in transfer org page 
> adjustment in modal border radius

### CODE REVIEW

**Comment by make-sundae** [comment]
Upon checking on my end there is an issue on my end that variable $csrf_token is undefined in changing email page

My guess is that the creation of token is missing?

Here is the [proof of testing](https://drive.google.com/file/d/1t22momydCV43vBRuPJzswTkVdcwigXse/view?usp=sharing)
image

**Comment by Andrea-Villalobos** [comment]
> Upon checking on my end there is an issue on my end that variable $csrf_token is undefined in changing email page
> 

Added this line
image


Just a question: the email in the SCO database must also be updated, right?

**Comment by make-sundae** [comment]
Email change now working

**Comment by make-sundae** [comment]
> Just a question: the email in the SCO database must also be updated, right?

As of my knowledge creating sco account is on per org registration and if that is the case it should be updated as well

Just to be sure let @Carl-Tabuso confirm this  if sco email should be updated as well.

**Comment by Carl-Tabuso** [comment]
> As of my knowledge creating sco account is on per org registration and if that is the case it should be updated as well
> 
> Just to be sure let @Carl-Tabuso confirm this if sco email should be updated as well.

Yes. Any updates on the information of a user should also be applied to the sco database.

**Comment by Andrea-Villalobos** [comment]
> > As of my knowledge creating sco account is on per org registration and if that is the case it should be updated as well
> > Just to be sure let @Carl-Tabuso confirm this if sco email should be updated as well.
> 
> Yes. Any updates on the information of a user should also be applied to the sco database.

This is noted, will update the code soon. Thank you.

**Comment by Andrea-Villalobos** [comment]
Proof of Testing: 



https://github.com/user-attachments/assets/38b60066-1208-41fb-80e8-ded0df0756ab


fix: update the email in sco db as well and add sending email modal - For Change Email/Information Page
fix: update cor in sco db as well and minor change in css - For Transfer Org

**Review by make-sundae — APPROVED** [review]

**Pull request merged**
