### PR TITLE
Master List & Account Setup

### PR DESCRIPTION
**Pull request by Carl-Tabuso**
# Features

- Implemented an email modal to handle email sending processes.
- Created an endpoint file for loading and managing the master list table data.
- Created draft content for emails used in account setup.
- Implemented password policy requirements on both client-side and backend validation.
- Added ajax to check which organizations are open for registration.
- Implemented a View More button on activity log so that on page load, it will only shows 5 set of logs.

# Fixes

- Cleaned up duplicate scripts in head and body elements.
- Added validation to handle cases where rows might be empty to prevent errors.
- Temporarily removed animation to resolve issues with "Get Started" label positioning on page load.

# Chores

- Verified and adjusted code related to organization variables.
- Created an endpoint to ensure entered email matches the user's ID.
- Adjusted styles to ensure responsiveness for mobile screen sizes of masterlist table.
- Created draft content for account setup-related email.
- Adjusted code to move the scroll-to-top button flagging outside the animation function.
- Commented-out unnecessary js code.
- Temporarily removed IP blocking functionality.

## Demos

Master list table and Account Setup

https://github.com/user-attachments/assets/b68889be-bebe-4c4d-8fd5-2fbc074701a8

Activity Log

https://github.com/user-attachments/assets/c51fa5f4-b2aa-4547-ac86-5bc38f7a8d66

> [!NOTE]
> I found a regression on activity log. The email address is gone when being filtered using dropdown.

### Database changes
[alter-voter-acc_status-tbl.txt](https://github.com/user-attachments/files/16364092/alter-voter-acc_status-tbl.txt)

### CODE REVIEW

**Comment by Carl-Tabuso** [comment]
### To-Do

- [x] Appropriate steps in "How To Setup Your Account"
- [ ] Appropriate text message on send email to setup account modal.

**Comment by Carl-Tabuso** [comment]
Remaining To-do task for UI and cosmetics will be assign a new issue ticket to me or other devs.

**Comment by biellamariscotes** [comment]
Most of the issues I've found are only front-end, the rest are fine.
- No loading screen while sending the email.

https://github.com/user-attachments/assets/eb45bf6e-b26e-4966-a1f7-7dc0c5290005

- Line inside the table during the empty state.
image

This can be merged. Tickets should be created to keep track of these issues.

**Review by biellamariscotes — APPROVED** [review]

**Comment by Carl-Tabuso** [comment]
> No loading screen while sending the email.

For the loading state, i might just have to do the same i did with the forgot password.

**Pull request merged**
