### PR TITLE
Updates schedule pages

### PR DESCRIPTION
**Pull request by make-sundae**
- Schedule configurations will be in blank state if the set schedule is done

  - will not update realtime

- Improvements on dark mode
- added formatting on faq configuration

### CODE REVIEW

**Comment by Carl-Tabuso** [comment]
Can i get snippets/snapshots or demo of the changes?

**Comment by make-sundae** [comment]
NOTE: Pages that uses script.js should add type of module in the script declaration
<script type="module" src="src/scripts/script.js" ></script>
if not change script may not work and cause error
**_Uncaught SyntaxError: Cannot use import statement outside a module (at script.js:1:1)_**

---

- Added Toast Alert on schedules

_**To import these, the script should be of type module**_

`<script type="module" src="src/scripts/script.js" defer></script>`

Can  be used by importing functions and classes

```
import {
    IsScheduleDone,
    NotificationManager,
    ElectionSchedule,
    RegistrationSchedule,
    registrationNotifHandler,
    electionNotifHandler,
    checkNotificationCookie,
    setNotificationCookie,
    createToast,
} from './configuration.js';
```

Then
 then calling the functions like this
**csrftoken_value** and **toastContainerHTMLRef** should be replaced by values or variables containing the value

```
electionWatcher = new ElectionSchedule({ csrf: csrftoken_value }, toastContainerHTMLRef);
registrationWatcher = new RegistrationSchedule({ csrf: csrftoken_value  }, toastContainerHTMLRef);

electionWatcher.fetch();
registrationWatcher.fetch();
```

**Comment by make-sundae** [comment]
Here is the changes on dark mode

https://drive.google.com/open?id=1eVBS1dthEp9vfff7m8fO3Ooo7o7xQLla&usp=drive_fs

**Comment by make-sundae** [comment]
Here is the changes on schedule pages
Resetting the schedule
https://drive.google.com/file/d/1eW6fGiE2cIWwIIXEesBVi7HIdRTb5EyB/view?usp=sharing

Toast notifs on schedule
https://drive.google.com/file/d/1eWXorB-iwkn2tm4AqPRfo-IL2JNntAi3/view?usp=sharing

**Comment by make-sundae** [comment]
Updates on faq


https://github.com/user-attachments/assets/01b868ae-7a3c-4ead-85e9-ee389c07825f

**Review by Carl-Tabuso — APPROVED** [review]
This'll do.

**Pull request merged**
