### PR TITLE
Preloader Implementation

### LINKED ISSUE #111: Preloader/Spinner
There is no implementation of Preloader/Spinner for every web page. Presently, there is no developer assigned to implement this feature. We will be using this GIF created by @Jeremie-Legrama 

### iVOTE Preloader

Loader

### PR DESCRIPTION
**Pull request by Carl-Tabuso**
# FEATURE

1. Introduces a preloader/spinner displayed every time the client requests the page. The preloader enhances the user experience by providing visual feedback while the page content is loading.

### Preloader Icon:
1. Added a custom icon for the preloader.
2. Ensured the icon is visually appealing and fits the overall design theme.

### Preloader Stylesheet:
1. Created a dedicated stylesheet `loader.css` for the preloader.
2. Applied styles to ensure the preloader is centered and appropriately sized.
3. Included animations for a smooth loading effect.

### Preloader Script:
1. Created a JavaScript file `loader.js` to manage the preloader's behavior.
2. Implemented a fade-out effect to smoothly transition from the preloader to the main content.
3. Ensured the preloader is hidden once the page has fully loaded.

### Preloader HTML File:
1. The `loader.html` is located at `src/includes/components` and consists of the following codes only:
```html
<!-- Loader -->
<div class="loader-wrapper">
    <div class="loader"></div>
</div>
``` 

## PROOF OF TESTING:

https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/assets/162773681/f36ae600-03e1-486f-9eeb-bf0ad0e8e3bd

**I have added `loader.css` and `loader.js` to all web pages except for `configuration.php` of @C-Ivan-Bandilla—I had issues on the preloader not appearing every time the page is loaded.**

**You may notice the changes in your head element and script, such as the following**

```html

    <link rel="stylesheet" href="styles/loader.css" />
    <script src="scripts/loader.js" defer></script>
```

...and for your body content. The `loader.html` is added.

```php
  <?php include_once FileUtils::normalizeFilePath(__DIR__ . '/includes/components/loader.html'); ?>
``` 

This shall close #111

### CODE REVIEW

**Comment by Carl-Tabuso** [comment]
Up @biellamariscotes

**Review by biellamariscotes — CHANGES_REQUESTED** [review]
The absence of loader in Configuration is acknowledged, but I noticed that the loader is not implemented on some pages, specifically:

- **About Us Page**

https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/assets/135019439/6c3add69-e199-4751-b8c6-b10128b753b8


<br>

- **Profile [Admin] Page**

https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/assets/135019439/e7dc5214-2c5e-415b-bbfa-3383313212dd

<br>

Kindly address this, or let me know if the lack of loader on these pages is intentional.

**Comment by biellamariscotes** [comment]
This PR can be merged once the requested adjustments have been made.

However, for the issues that have been identified (see below), I can create separate issues for them so that it can be tracked and addressed by the assigned developers.

<hr>

### Issues Identified
- **Ballot Forms**
Loader is being doubled when page has been refreshed/accessed.

https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/assets/135019439/715f9e89-c60c-4866-adc9-710c6022953a

<br>

- **Log In: Forgot Password Modal.**
The page refreshes when "Cancel" is clicked in the Forgot Password modal. This should be addressed by the developer(s) handling the Log In module. The issue seems related to the JavaScript codes handling the modal and form submission.

https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/assets/135019439/9898c8a4-b5c4-4585-9b21-7725df2728a2

**Comment by Carl-Tabuso** [comment]
> The absence of loader in Configuration is acknowledged, but I noticed that the loader is not implemented on some pages, specifically:
> 
> * **About Us Page**
> 
>  PRELOADER.About.Us.mp4 
> 
> * **Profile [Admin] Page**
> 
>  PRELOADER.No.loader.in.Profile.and.Configuration.mp4 
> 
> Kindly address this, or let me know if the lack of loader on these pages is intentional.

For the "About Us" page, are we going to leave it as is? Whenever it's clicked, I thought the page should scroll down to its content instead of redirection. As for the "Profile" page, I will do a follow-up commit as I had just finished merging Daven's pull request for that page. Going back to the "About Us" page, tell me if I got it wrong.

For "Ballot Forms" I will fix this right away. As for the "Forgot Password", I let the page reload everytime the Cancel button is clicked. Reason for that is when it's just simply dismissed, the values inputted by the user or any error messages in there remains upon clicking the "Forgot Password" again.

**Comment by biellamariscotes** [comment]
> For the "About Us" page, are we going to leave it as is? Whenever it's clicked, I thought the page should scroll down to its content instead of redirection. As for the "Profile" page, I will do a follow-up commit as I had just finished merging Daven's pull request for that page. Going back to the "About Us" page, tell me if I got it wrong.

For consistency, I think the application of the loader in **About Us** is recommended.

> ...As for the "Forgot Password", I let the page reload everytime the Cancel button is clicked. Reason for that is when it's just simply dismissed, the values inputted by the user or any error messages in there remains upon clicking the "Forgot Password" again.

Thanks for clarifying the issue with the Cancel button. Though, to improve user experience, I suggest making an exception (page refreshing) to closing the modal when the input field is empty. This is a recommendation, and can be later on addressed by future PRs.

**Comment by Carl-Tabuso** [comment]
> > For the "About Us" page, are we going to leave it as is? Whenever it's clicked, I thought the page should scroll down to its content instead of redirection. As for the "Profile" page, I will do a follow-up commit as I had just finished merging Daven's pull request for that page. Going back to the "About Us" page, tell me if I got it wrong.
> 
> For consistency, I think the application of the loader in **About Us** is recommended.

Okay. Let me do a follow-up commit.
> 
> > ...As for the "Forgot Password", I let the page reload everytime the Cancel button is clicked. Reason for that is when it's just simply dismissed, the values inputted by the user or any error messages in there remains upon clicking the "Forgot Password" again.
> 
> Thanks for clarifying the issue with the Cancel button. Though, to improve user experience, I suggest making an exception (page refreshing) to closing the modal when the input field is empty. This is a recommendation, and can be later on addressed by future PRs.

Got it. You may just tagged this pull request with a "need issue ticket" label or assign the new issue ticket right away.

**Comment by biellamariscotes** [comment]
> ...You may just tagged this pull request with a "need issue ticket" label or assign the new issue ticket right away.

I'll assign an issue for this soon.

**Review by biellamariscotes — APPROVED** [review]
Changes have been acknowledged, will now merge.

**Pull request merged**
