### PR TITLE
feat: add backend of information page

### PR DESCRIPTION
**Pull request by Andrea-Villalobos**
Not really sure if working since I am using few emails to test it out.

https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/assets/162780943/53dd54fe-a742-440e-89ac-d486d98b1802

### CODE REVIEW

**Comment by make-sundae** [comment]
Email sending is okay

However I am clueless why what email are allowed

https://drive.google.com/file/d/1q-9OoHBsLQDAY6sBwMk97ZLHjp5wwLu_/view?usp=sharing


is also clipped
jennymaelbaldoza@iskolarngbayan.pup.edu.ph
https://drive.google.com/file/d/1pinZFqYJJ9ixXrYL83dxyM6ArW2NjyKz/view?usp=sharing


also tried to update using email then c.ivanbandi1lla@gmail.com
but just reload the page 

do I need additional updates to db?

**Comment by make-sundae** [comment]
Apologies for the music included in recording
just noticed now

**Comment by make-sundae** [comment]
also noticed that my password is exposed in URL

image

**Comment by Carl-Tabuso** [comment]
Please follow up on this soon @Andrea-Villalobos

**Comment by Andrea-Villalobos** [comment]
I successfully changed my email here.
Apologies for the late response.

https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/assets/162780943/ded066b8-98e4-4e54-835e-e3738d1dc13f

**Review by make-sundae — APPROVED** [review]
Working now

however client side  validation become less restrictive

**Pull request merged**
