### PR TITLE
fix: Implement AJAX for Dropdowns of the Election Reports Module

### LINKED ISSUE #148: ER: Session Start
Include the `session-handler.php` file instead of using the `session_start()` in `fetch_candidates.php` file. Follow the kebab naming convention—use hypens instead of underscores. 

Code block:
```php
<?php
session_start();
include_once str_replace('/', DIRECTORY_SEPARATOR, 'includes/classes/file-utils.php');
require_once FileUtils::normalizeFilePath('includes/classes/db-connector.php');
```

### LINKED ISSUE #149: ER: PHP File Path
Put every PHP action script inside the `includes` folder or you may create a new folder in there. Do as you see fit. All files under the `src` folder must be the web pages only.

This includes `fetch_candidates.php` and `result.pdf`

image

### LINKED ISSUE #151: ER: Implement AJAX for Dropdowns
Use AJAX to your A.Y. Election Year dropdown selection to prevent the page from reloading whenever an option is selected. 

https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/assets/162773681/69e69b4d-e3a0-4d7c-b66f-7858f283ee36

Keep this in mind with other dropdowns, such as the positions dropdown located at the bottom right of the bar graph.

image

### PR DESCRIPTION
**Pull request by AraojoBenedict**
Implemented AJAX for Dropdowns of the Election Reports Module
Closes #151 
Closes #148 
Closes #149 
Screen Shot for proof of issue 148 and 149:
image
image

Screenshot for proof:
image
Screen Record for proof of issue 151:

https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/assets/162650843/f9b75275-5341-407d-a3b9-9fa135cb73fc

Fix: Order of the drop down list in the bar chart
 Screenshot for proof:
image

### CODE REVIEW

**Review by Carl-Tabuso — COMMENTED** [review]
You can still modularize your codes. It's still not properly indented and quite hard to read. As for the UI, await for @biellamariscotes feedback before we proceed with merging.

I suggest you put all these javascript codes from `result-generation.php` into a separate javascript file.

### CODE BLOCKS

Line 180-202:
```javascript
<script>
    function selectYear(year) {
        const xhttp = new XMLHttpRequest();
        xhttp.onreadystatechange = function() {
            if (this.readyState === 4 && this.status === 200) {
                document.getElementById("election-results").innerHTML = this.responseText;
                document.getElementById("selectedYear").innerHTML = "Current Academic Year: <strong>" + year + "</strong>";
                // Update the global selected year
                window.selectedYear = year;
                // Update the dropdown button text
                document.getElementById("dropdownButtonText").innerHTML = "A.Y. " + year + ' <i data-feather="chevron-down" class="white im-cust feather-1xs"></i>';
                // Reinitialize feather icons
                feather.replace();
                // Trigger position select change to update the chart with the new year
                document.getElementById('positionSelect').dispatchEvent(new Event('change'));
            }
        };
        xhttp.open("GET", "includes/fetch-election-data.php?election_year=" + year, true);
        xhttp.send();
    }

    // Initialize global selected year
    window.selectedYear = '<?php echo $selected_year; ?>';
</script>
``` 

Line 235 -289:
```javascript
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script>
    var ctx = document.getElementById('myChart').getContext('2d');
    var myChart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: [], // Initially empty
            datasets: [{
                label: '# of Votes',
                data: [], // Initially empty
                backgroundColor: 'rgba(54, 162, 235, 0.2)',
                borderWidth: 1,
                barThickness: 40
            }]
        },
        options: {
                plugins: {
                    legend: {
                        display: false
                    }
                },
                scales: {
                    y: {
                        beginAtZero: true,
                    },
                    x: {
                        grid: {
                            display: false
                        }
                    }
                }
            }
        });

function updateChart(labels, data) {
    myChart.data.labels = labels;
    myChart.data.datasets[0].data = data;
    myChart.update();
}

document.getElementById('positionSelect').addEventListener('change', function () {
    var selectedPosition = this.value;
    var electionYear = '<?php echo $selected_year; ?>';

    fetch(`fetch_candidates.php?position_id=${selectedPosition}&election_year=${electionYear}`)
        .then(response => response.json())
        .then(data => {
            console.log(data);
            var labels = data.candidates.map(candidate => candidate.name);
            var votes = data.candidates.map(candidate => candidate.vote_count);
            updateChart(labels, votes);
        });
});
</script>
``` 

Line 551-597:
```javascript

<script>
        function selectPosition(title, positionId) {
            document.getElementById("selectedPosition").innerHTML = title;
            window.location.href = "?position_id=" + positionId;
        }

        //for dropdown download
        window.onclick = function(event) {
        if (!event.target.matches('.dropdown-button2')) {
            var dropdowns = document.getElementsByClassName("dropdown-content2");
            for (var i = 0; i < dropdowns.length; i++) {
            var openDropdown = dropdowns[i];
            if (openDropdown.style.display === "block") {
                openDropdown.style.display = "none";
            }
            }
        }
        }

        // Attach event listeners to rating and feedback inputs to update button text
        ratingInput.addEventListener('input', updateButtonText);
        feedbackInput.addEventListener('input', updateButtonText);


        // Selecting emoji, no initial selected emoji
        document.querySelectorAll('.feedback li').forEach(entry => entry.addEventListener('click', e => {
        if (entry.classList.contains('active')) {
            entry.classList.remove('active');
        } else {
            document.querySelector('.feedback li.active')?.classList.remove('active');
            entry.classList.add('active');
        }
        e.preventDefault();
        }));

        // Add value of the rating, corresponding with the emoji selected
        document.addEventListener("DOMContentLoaded", function() {
        var feedbackOptions = document.querySelectorAll(".feedback li");

        feedbackOptions.forEach(function(option) {
            option.addEventListener("click", function() {
                var value = this.getAttribute("data-value");
                document.getElementById("rating").value = value;
            });
        });
        });
</script>
``` 

Line 604 - 678:
```javascript
<script>
    document.addEventListener("DOMContentLoaded", function() {
        const candidates = document.querySelectorAll('.card-candidate');
        const btnPrevious = document.querySelector('.btn-previous');
        const btnNext = document.querySelector('.btn-next');
        const candidatesPerPage = 5;
        let currentPage = 0;

        function showPage(pageNumber) {
            for (let i = 0; i < candidates.length; i++) {
                if (i >= pageNumber * candidatesPerPage && i < (pageNumber + 1) * candidatesPerPage) {
                    candidates[i].style.display = 'block';
                } else {
                    candidates[i].style.display = 'none';
                }
            }
        }

        showPage(currentPage);

        btnPrevious.addEventListener('click', function() {
            if (currentPage > 0) {
                currentPage--;
                showPage(currentPage);
            }
        });

        btnNext.addEventListener('click', function() {
            const totalPages = Math.ceil(candidates.length / candidatesPerPage);
            if (currentPage < totalPages - 1) {
                currentPage++;
                showPage(currentPage);
            }
        });
    });
</script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.9.3/html2pdf.bundle.min.js"></script>
<script>
    function downloadPDF() {
        fetch('result-pdf.php?election_year=<?php echo $election_year; ?>')
        .then(response => response.text())
        .then(phpString => {
        const options = {
            margin: 10,
            filename: 'generated_pdf.pdf',
            image: { type: 'jpeg', quality: 0.98 },
            html2canvas: { scale: 2 },
            jsPDF: { unit: 'mm', format: 'a4', orientation: 'landscape' }
        };

        html2pdf().from(phpString).set(options).save();
        })
        .catch(error => {
        console.error('Error fetching PHP content:', error);
        });
    }

    function alldownloadPDF() {
        fetch('allresult-pdf.php?election_year=<?php echo $election_year; ?>')
        .then(response => response.text())
        .then(phpString => {
        const options = {
            margin: 10,
            filename: 'generated_pdf.pdf',
            image: { type: 'jpeg', quality: 0.98 },
            html2canvas: { scale: 2 },
            jsPDF: { unit: 'mm', format: 'a4', orientation: 'landscape' }
        };

        html2pdf().from(phpString).set(options).save();
        })
        .catch(error => {
        console.error('Error fetching PHP content:', error);
        });
    }
</script>
```

**Comment by Carl-Tabuso** [comment]
Does this urgently need to be merged? I can assign you new issue tickets if so.

**Comment by AraojoBenedict** [comment]
Yes if its okay to be merged, will address the issue in the next PR. Thank you

**Review by Carl-Tabuso — APPROVED** [review]
Will issue a ticket.

**Pull request merged**
