### PR TITLE
fix: Changed Registration page to fit current database, included CSRF…

### LINKED ISSUE #112: Registration Script
## Registration

Use the `session-handler.php` file instead of `session_start();` in your `registration-process.php` file.

Code block from .../src/includes/registration-process.php:
```php
<?php
session_start();
include_once str_replace('/', DIRECTORY_SEPARATOR, __DIR__ . '/classes/file-utils.php');
require_once FileUtils::normalizeFilePath('classes/db-config.php');
require_once FileUtils::normalizeFilePath('error-reporting.php');
``` 

Error logs:
```
2024-05-28 11:53 am Error: [2] ini_set(): Session ini settings cannot be changed when a session is active - C:\xampp\htdocs\PUPSRC-AutomatedElectionSystem\src\includes\session-handler.php: 7
2024-05-28 11:53 am Error: [2] ini_set(): Session ini settings cannot be changed when a session is active - C:\xampp\htdocs\PUPSRC-AutomatedElectionSystem\src\includes\session-handler.php: 8
2024-05-28 11:53 am Error: [2] session_set_cookie_params(): Session cookie parameters cannot be changed when a session is active - C:\xampp\htdocs\PUPSRC-AutomatedElectionSystem\src\includes\session-handler.php: 10
2024-05-28 11:53 am Error: [8] session_start(): Ignoring session_start() because a session is already active - C:\xampp\htdocs\PUPSRC-AutomatedElectionSystem\src\includes\session-handler.php: 18
```

### LINKED ISSUE #131: Registration Page: File Hashing

### LINKED ISSUE #132: Registration Page: Secure Form Submission
### Avoiding Cross-Site Request Forgery

Generate a CSRF token to be validated in the server-side once a user submits the form.

### PR DESCRIPTION
**Pull request by Peter-Escueta**
**DISCLAIMER YOU WILL NEED COR_HASH IN THE VOTER TABLE OF THE DATABASE cor_hash - varchar - 64 length**
fixed #112 :
image
fixed #131 :
image
( Assuming COR Hashing is for file integrity validation otherwise considering hashing typically happens one way, it'll be hard to use to display the COR pdf itself)
Added CSRF token in form field and form submission processing  to fix #132 
Additional Changes:
*Changed Password Regex
*Made Confirm Password Checking to happen 3 seconds after typing
*Put space prevention in Email, Password and Confirm Password
*removed core.css color basis on admindashboard

### CODE REVIEW

**Comment by biellamariscotes** [comment]
image

Note about commit [a136b8a](https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/pull/142/commits/a136b8aa7ed4b756d46b024911c2c46e31c99f17):
- All commit messages must include a commit type, no matter how small the changes are. Kindly adhere to proper commit practices.

**Review by Carl-Tabuso — APPROVED** [review]
Will work on this.

**Comment by Carl-Tabuso** [comment]
Provide a php script for this change
> DISCLAIMER YOU WILL NEED COR_HASH IN THE VOTER TABLE OF THE DATABASE cor_hash - varchar - 64 length

**Comment by Peter-Escueta** [comment]
> Provide a php script for this change
> 
> > DISCLAIMER YOU WILL NEED COR_HASH IN THE VOTER TABLE OF THE DATABASE cor_hash - varchar - 64 length

The php script can be seen in the link below:
https://drive.google.com/file/d/1OsOMtIGBe_SQTpQnpoNeQbURtS2iCdyy/view?usp=sharing

**Pull request merged**
