### PR TITLE
feat: Add phpspreadsheet library

### PR DESCRIPTION
**Pull request by LZionDEVQA**
**Overview**

**Documentation**

PHP 7.4 or later
Composer

_Installation Steps_

1. Open your terminal.
2. Navigate to your project folder.
3. Install PHPSpreadsheet using Composer.
4. If you get an error about missing extensions (like GD), install them:

For Windows: Enable the **extension=gd** and **extension=zip** in php.ini

**Additional Information**
-This library is installed in the vendor folder and will be used for importing/exporting voters in the system
-This library is needed as the xlsx/xls and csv files need to use the phpspreadsheet library
-Activity log is also included here in this PR
**-This can be tested now.**

This will only accept 'Student ID, Last Name', 'First Name', 'Middle Name', 'Suffix', 'Year Level', 'Section', 'Email' the COR cannot be imported within the excel/csv file as it was not possible. In excel and csv, the PDF is only imported as object and not the file itself.

The following are automatically:
$role = 'student_voter';
$accountStatus = 'for_verification';
$voterStatus = 'active';
$voteStatus = NULL;

for csv/excel sample files, it can be found here: https://drive.google.com/drive/folders/1O_q27gTnlqtNn-Fk0q4zZWPpa29S1lnJ?usp=drive_link

this will close the #258 issue

### CODE REVIEW

**Comment by make-sundae** [comment]
> For Windows: Enable the extension in php.ini

when needed its better if you can provide the line or name

confirm if this is correct

image

**Comment by LZionDEVQA** [comment]
@C-Ivan-Bandilla Yes, that's correct. I've updated the overview of this pr regarding this. Thank you.

**Comment by Carl-Tabuso** [comment]
UP @biellamariscotes  @C-Ivan-Bandilla  @Andrei-Matibag

**Comment by Carl-Tabuso** [comment]
@Andrei-Matibag is the import function working now? If so, can you provide a demo?

**Comment by LZionDEVQA** [comment]
@Carl-Tabuso this is the demo for import that the function is working.

https://github.com/user-attachments/assets/38ae0900-96ef-4da7-9ea3-06c1b3b79caf

**Comment by Carl-Tabuso** [comment]
> @Carl-Tabuso this is the demo for import that the function is working.
> 
>  2024-07-16.20-50-30.mp4

I suggest that upon uploading an invalid file, it should be validated at that very moment. You don't wait for the user to hit the button before showing the modal.

**Comment by LZionDEVQA** [comment]
> > @Carl-Tabuso this is the demo for import that the function is working.
> > 2024-07-16.20-50-30.mp4
> 
> I suggest that upon uploading an invalid file, it should be validated at that very moment. You don't wait for the user to hit the button before showing the modal.

It's not an invalid file, It's an invalid format of the content inside the csv/xls file

**Comment by LZionDEVQA** [comment]
I have the validation for an invalid file

**Comment by LZionDEVQA** [comment]
> > > @Carl-Tabuso this is the demo for import that the function is working.
> > > 2024-07-16.20-50-30.mp4
> > 
> > 
> > I suggest that upon uploading an invalid file, it should be validated at that very moment. You don't wait for the user to hit the button before showing the modal.
> 
> It's not an invalid file, It's an invalid format of the content inside the csv/xls file

I'm sorry for not showing it clearly

**Comment by Carl-Tabuso** [comment]
Ohh ok, I get it now. That means if the file contents are invalid, there should be a different warning modal, but in your case you simply recycled the modal for invalid file and max 25mb of size, correct?

**Comment by LZionDEVQA** [comment]
> Ohh ok, I get it now. That means if the file contents are invalid, there should be a different warning modal, but in your case you simply recycled the modal for invalid file and max 25mb of size, correct?

Yes. I base on Figma. So I didn't add another modal for it

**Comment by Carl-Tabuso** [comment]
> Yes. I base on Figma. So I didn't add another modal for it 

You should perhaps just change the modal title and contents in this case and have it sent to our gc.

**Comment by LZionDEVQA** [comment]
> > Yes. I base on Figma. So I didn't add another modal for it
> 
> You should perhaps just change the modal title and contents in this case and have it sent to our gc.

Okay i'll code it and make a pr. I'll send it to our gc too

**Comment by LZionDEVQA** [comment]
@Carl-Tabuso I have a question regarding the export functionality. Are we still gonna add it? In just my point of view it is repetitive because the user already imported those list of students why still export? But if we still gonna add it, in what page should we put the export functionality? There's no update in figma about this so I asked.

**Comment by Carl-Tabuso** [comment]
> @Carl-Tabuso I have a question regarding the export functionality. Are we still gonna add it? In just my point of view it is repetitive because the user already imported those list of students why still export? But if we still gonna add it, in what page should we put the export functionality? There's no update in figma about this so I asked.

Yes, exporting files can also be used to preserve and copy old accounts in the event of permanent deletion or data migration.

About the export UI, I'll ask Yuri and others to provide an update.

**Comment by LZionDEVQA** [comment]
> > @Carl-Tabuso I have a question regarding the export functionality. Are we still gonna add it? In just my point of view it is repetitive because the user already imported those list of students why still export? But if we still gonna add it, in what page should we put the export functionality? There's no update in figma about this so I asked.
> 
> Yes, exporting files can also be used to preserve and copy old accounts in the event of permanent deletion or data migration.
> 
> About the export UI, I'll ask Yuri and others to provide an update.

Thank you @Carl-Tabuso

**Comment by Carl-Tabuso** [comment]
Is the arrangement of columns here is what will be followed across all orgs — have you talked abut this matter with biella? If so, we may proceed with the merging of this pr

**Comment by Carl-Tabuso** [comment]
I have an issue with the file input field allowing attachments of pdf. You should add a client-side validation for this. We don't wait for the user to click the button, for him to realize he uploaded a wrong file extension. Kind of like how it works in the registration page. Upon import, the file size and extension is validated on the client-side but also on the server-side later. It bothers me that there is a page reload after clicking the import voters or close button. You can implement ajax for this.

https://github.com/user-attachments/assets/cb8f6dec-4d7a-47c3-a4f9-cd8821d4b6c7

**Comment by Carl-Tabuso** [comment]
It's quite unclear also to say that there's a duplicate of users found if those user accounts are in the recycle bin. What you can do is rephrase the modal. You can still say that there's a duplicate found and they may also check the recycle bin for such duplicates. You should also add a button state if the server-side is processing the data from the imported file. From the video below, the Import Voters button is vulnerable to shotgun clicks. And yes, the page reload is uncalled for.


Take a closer look here:


https://github.com/user-attachments/assets/5f07ccd0-9290-4390-a5dd-a83c3c8db340

**Comment by LZionDEVQA** [comment]
> Is the arrangement of columns here is what will be followed across all orgs — have you talked abut this matter with biella? If so, we may proceed with the merging of this pr

We talked about it. She sends the format but we will follow the format I sent. I will just insert the Student ID column as the first header

**Comment by LZionDEVQA** [comment]
> It's quite unclear also to say that there's a duplicate of users found if those user accounts are in the recycle bin. What you can do is rephrase the modal. You can still say that there's a duplicate found and they may also check the recycle bin for such duplicates. You should also add a button state if the server-side is processing the data from the imported file. From the video below, the Import Voters button is vulnerable to shotgun clicks. And yes, the page reload is uncalled for.
> 
> Take a closer look here:
> 
>  2024-07-17.13-50-04.mp4

I managed to fix this. It will reject the import process even if there's a single invalid data or format in the excel file. It will not be vulnerable to shotgun clicks because it will keep showing the invalid modal.

**Comment by LZionDEVQA** [comment]
I will update my pr and the format in the google drive

**Comment by LZionDEVQA** [comment]
I included the Student ID but it will not saved in the DB. I disable the button while importing.

https://github.com/user-attachments/assets/08ca82c2-68d1-4723-beb0-e3599ec2b57c

**Comment by LZionDEVQA** [comment]
I updated the sample formats in the google drive

**Comment by make-sundae** [comment]
Does it check the file for duplicates entries? 
image
image


[Sample-Voters.csv](https://github.com/user-attachments/files/16277004/Sample-Voters.csv)

https://drive.google.com/file/d/1t42Kqb5xGiMn6pqdFVYss4GqExUSRjCJ/view?usp=sharing

**Comment by LZionDEVQA** [comment]
> Does it check the file for duplicates entries? image image
> 
> [Sample-Voters.csv](https://github.com/user-attachments/files/16277004/Sample-Voters.csv)
> 
> https://drive.google.com/file/d/1t42Kqb5xGiMn6pqdFVYss4GqExUSRjCJ/view?usp=sharing

does it have same student ID?

**Comment by make-sundae** [comment]
> does it have same student ID?

Yes it has 
image
image

This may be user fault but may cause issues in the system if not handled especially if the number of imported users are numerous
such as resetting password by email may fail and etc.

**Comment by LZionDEVQA** [comment]
> I have an issue with the file input field allowing attachments of pdf. You should add a client-side validation for this. We don't wait for the user to click the button, for him to realize he uploaded a wrong file extension. Kind of like how it works in the registration page. Upon import, the file size and extension is validated on the client-side but also on the server-side later. It bothers me that there is a page reload after clicking the import voters or close button. You can implement ajax for this.
> 
>  2024-07-17.13-42-34.mp4

I managed to fix this. I disabled the button when putting a file other than csv/xls file. I also include the modal of invalid file format

**Comment by LZionDEVQA** [comment]
> > does it have same student ID?
> 
> Yes it has image image
> 
> This may be user fault but may cause issues in the system if not handled especially if the number of imported users are numerous such as resetting password by email may fail and etc.

I fixed this. I put a validation to check duplication of the prefix of email and the "00000" part of the student ID within the file and database for the email

**Comment by LZionDEVQA** [comment]
> > > does it have same student ID?
> > 
> > 
> > Yes it has image image
> > This may be user fault but may cause issues in the system if not handled especially if the number of imported users are numerous such as resetting password by email may fail and etc.
> 
> I fixed this. I put a validation to check duplication of the prefix of email and the "00000" part of the student ID within the file and database for the email

If there's a problem in the Student ID part. I'll try to fix it as soon as possible

**Comment by make-sundae** [comment]
> If there's a problem in the Student ID part. I'll try to fix it as soon as possible

Will check right now

**Review by make-sundae — APPROVED** [review]
Apologies for late review this can be merge 

An additional suggestion is that when are duplicate entries in a valid file
The system can proceed inserting voters but will not insert duplicates instead of showing the invalid modal.

**Comment by Carl-Tabuso** [comment]
Does this not need an issue ticket label?

**Pull request merged**
