### PR TITLE
Activity Log

### LINKED ISSUE #255: Create Audit/Action Logs

### PR DESCRIPTION
**Pull request by Carl-Tabuso**
#### This should close #255 

# Features:
- Implemented the UI for Activity Log with complete functionalities.
- Added dropdown filtering features for head admin to filter activities among voters and admin.
- Linked activity log page to header CTA.

# Fix
- Converted FAQ image format to .webp for optimized web performance.

# Chore
- Created constants config file for uniform log messages.
- Developed utility class for capturing user browser details, IP address, and email.
- Added event listeners for scroll-to-top button, popover, and AJAX filtering.

# Style
- Designed responsive stylesheet for activity log page across all devices.

## How to use

- Refer to the `logger.php` https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/commit/74e9c63250b092b562ff80f1f4f548aaa4d9689e class located at `src/includes/classes` directory. There, you can read the comments on how to implement the class along with the config file called `constants.php` https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/commit/89c5237239335e4c54450b550e5b39a0b4690ba4 located at `src/includes` directory.

_Code block - sample implementation_

```php
/*
 * This is a utility class for logging the activity of your page user.
 * You can configure the constants.php file located in includes directory
 * for additional actions and such.
 * To log the activity of your user, you can instantiate a new instance of
 * this class and pass the $role and $action arguments and then call the 
 * logActivity() method on your endpoint.
 * 
 * Example Usage using a superglobal session variable:
*/
 $logger = new Logger($_SESSION['role'], LOGIN);
 $logger->logActivity();

/*
 * You can also explicitly pass the role of your user as the argument.
 * Example: 
*/
 $logger = new Logger(ROLE_ADMIN, LOGIN);
 $logger->logActivity();

``` 

You may also check how it was implemented in the `logout.php` file [here,](https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/compare/AT7-138-ActivityLog?expand=1#diff-95a3c4d70a37b6bc7b18d7c9cc421f8311a3fbbccfa13160f060ec0228fb7d7a)

### Student/Admin Interface

https://github.com/user-attachments/assets/e3026f3f-70fe-45c5-8677-29ebf5a768ed

### Head Admin Interface

https://github.com/user-attachments/assets/10a5adab-d007-4a98-b4f6-453059e3d866

### Responsiveness

https://github.com/user-attachments/assets/4eb0d6fe-fb12-4dd8-b6e3-340bcc24cbc9

### Firefox Browser

https://github.com/user-attachments/assets/c522afc3-d396-4f76-9715-ecac96d44cd1

> [!NOTE]
> In case your page/module requires user action that was not included in the `constants.php` feel free to modify it accordingly.

### CODE REVIEW

**Comment by Carl-Tabuso** [comment]
I forgot the sql for this. Give me a second.

> I forgot the sql for this. Give me a second.

Here ya go:  [create-activitylog.txt](https://github.com/user-attachments/files/16217364/create-activitylog.txt)

**Comment by make-sundae** [comment]
While waiting for sql here is some ui issues on empty state when on 1440 px wide

https://drive.google.com/file/d/1t2M4eEHUDS1zafiesE8MOaRLp15NOF05/view?usp=sharing

**Comment by Carl-Tabuso** [comment]
> While waiting for sql here is some ui issues on empty state when on 1440 px wide
> 
> https://drive.google.com/file/d/1t2M4eEHUDS1zafiesE8MOaRLp15NOF05/view?usp=sharing

Yep, i've been wrapping my head around about what's causing this issue but no luck. Will try to look for solution elsewhere.

**Comment by make-sundae** [comment]
> Here ya go: [create-activitylog.txt](https://github.com/user-attachments/files/16217364/create-activitylog.txt)

Tried downloading 3 times
I think it is blank txt file

image

**Comment by Carl-Tabuso** [comment]
> Tried downloading 3 times
> I think it is blank txt file

Can you try again: [create-activitylog.txt](https://github.com/user-attachments/files/16223618/create-activitylog.txt)

**Review by make-sundae — APPROVED** [review]
Works fine on my end


https://github.com/user-attachments/assets/2f419e57-2250-4095-8b37-c6df8228e401

**Comment by Carl-Tabuso** [comment]
For improvement: Fetch data asynchronously to reduce page load.

**Pull request merged**
