### PR TITLE
Fixed and added features to Configuration/fix candidate position

### PR DESCRIPTION
**Pull request by make-sundae**
- Fixed issue where input placeholder is cut off

- Added add  and edit modal for position name and duties and responsibilities
- Known bug where adding new position and then canceling will immediately add a new row.
- Fixed affected page of temporarily disabling regenerateSessionID 

- Rich Text Editor Toolbar is not aligned to figma UI.
Will try to copy in the next commits
image
image

Code is messed will refactor on next commits

### CODE REVIEW

**Review by Carl-Tabuso — CHANGES_REQUESTED** [review]
I've mainly tested your candidate positions code on my end and have acknowledged the errors you've described. 

- Save button is not working
- Description reflects on the candidates table: description column but not properly sanitized.
- May i know if you are going to proceed with the configuration dropdown in the sidebar or adhere with what's on the mockup UI?

Can you make it until 4pm today to fix the footer not sticking to the bottom?

1. Ballot Forms

image

2. Schedule

image

3. Election Year

image


4. Voting Guidelines

image

5. Candidate Positions

image

**Comment by C-Ivan-Bandilla** [comment]
> I've mainly tested your candidate positions code on my end and have acknowledged the errors you've described.
> 
> * Save button is not working
> * Description reflects on the candidates table: description column but not properly sanitized.
> * May i know if you are going to proceed with the configuration dropdown in the sidebar or adhere with what's on the mockup UI?
> 
> Can you make it until 4pm today to fix the footer not sticking to the bottom?
> 
> 1. Ballot Forms
> 
> image
> 
> 2. Schedule
> 
> image
> 
> 3. Election Year
> 
> image
> 
> 4. Voting Guidelines
> 
> image
> 
> 5. Candidate Positions
> 
> image

I will just comment updates to the sidebar to restore the previous look of the sidebar.

Will update soon after fixing proposed changes before 4 pm

**Comment by C-Ivan-Bandilla** [comment]
I apologize for late commit 

changes are 
 revert the sidebar
 temporary quick fix for footer
 striped functionality of reordering candidate position to remove buggy code for now
 I added some dummy front end for blank pages in configuration

**Comment by Carl-Tabuso** [comment]
> I apologize for late commit
> 
> changes are revert the sidebar temporary quick fix for footer striped functionality of reordering candidate position to remove buggy code for now I added some dummy front end for blank pages in configuration

will check this in a moment

**Pull request closed without merging**
