### PR TITLE
AT4-108-Settings-Password

### PR DESCRIPTION
**Pull request by Ivan-Edan**
**Description:** This PR is all about the Settings page of the User side. To be specific is the Password Change Module.
Sample Output:
image
image

**What not yet implemented and needs adjustments:**
- Need to add back-end function
- Might fix responsiveness in some parts
- Check mark in resetting password

### CODE REVIEW

**Review by Andrea-Villalobos — COMMENTED** [review]
Apologies for the late review. There are just minor differences from yours and in the figma:


- The placeholder text in the current password text field has no space or padding; it is right up against the left side.
- Confirm Button must be initially disabled
image


- Password Updated Modal 
Kindly adjust the modal width, button padding, and font size.

Yours
Screenshot 2024-06-30 094521
vs
Figma
Screenshot 2024-06-30 094507

I am planning to fix the css style for this so I am disregarding this part. 
Screenshot 2024-06-30 100022

**Comment by Carl-Tabuso** [comment]
image

Change the text from **Redirecting to login page** to **Redirecting to landing page**

We are terminating the session of the user on successful changed of password.

**Comment by Ivan-Edan** [comment]
Screenshot (87)
Screenshot (88)
Fix the padding of the text field and added the disable for the button
Fix the Redirecting to login page to Redirecting to landing page

**Comment by Carl-Tabuso** [comment]
Is this responsive on screen of all sizes?

**Comment by Ivan-Edan** [comment]
it is responsive in certain mobile sizes upon testing

**Comment by Carl-Tabuso** [comment]
> it is responsive in certain mobile sizes upon testing

can you provide screenshots, especially on 320px breakpoint.

@Andrea-Villalobos please have this thoroughly tested, especially on text length truncations.

**Comment by Carl-Tabuso** [comment]
Update please.

**Comment by Andrea-Villalobos** [comment]
Will review in a while. Thank you.

**Comment by Andrea-Villalobos** [comment]
Font sizes should be adjusted; there are no other major flaws

Are you going to adjust the font size or should I approve this and address this issue in your next pr? @Ivan-Edan 

Screenshot 2024-07-01 001317


Screenshot 2024-07-01 001249

**Comment by Carl-Tabuso** [comment]
Tag the `need issue ticket` if needed so you or I can return to this PR for another review. Bye :running_man:

**Comment by Ivan-Edan** [comment]
ill try to change the font size on the next pr @Andrea-Villalobos

**Review by Andrea-Villalobos — APPROVED** [review]
Just adjust the font and improve

**Pull request merged**
