### PR TITLE
Sidebar Toggle Icon

### PR DESCRIPTION
**Pull request by yojibeans**
- Only added the script in the issued bug
- Changed reset-password icon from png to webp
- Fixed the border radius of change password
- Change Password was made responsive
- Moved to a separate file the css of change password

### CODE REVIEW

**Review by Carl-Tabuso — COMMENTED** [review]
On change password page, the margin top from the header seems a little too big. And the footer isn't supposed to look like this.

image

**Comment by Carl-Tabuso** [comment]
image

this doesn't look the same with what's on the mockup UI. The button isn't even centered properly

**Comment by yojibeans** [comment]
addressed

**Comment by Carl-Tabuso** [comment]
I'm having this issue on my end. I have tried to hard reset/refresh my browser.

https://github.com/user-attachments/assets/c8749b85-c323-4d67-a82f-e8f32d1c3b06

**Comment by yojibeans** [comment]
My bad, those were my debugging codes from responsiveness

**Comment by F-Seannnnnn** [comment]
> this doesn't look the same with what's on the mockup UI. The button isn't even centered properly

This is Carl. Did check the latest changes made and the concern above is yet to be addressed on change password page. Please finish this ASAP—this is just frontend.

**Comment by yojibeans** [comment]
Was the issue with regards to the centering of the card? Like its on the right side? If yes, it seemed fine on my end as well on Ivan's end so I don't know why or how did you get that issue.

I already addressed the centering of  button. The issue was using wrong attribute on the inline code.

**Comment by biellamariscotes** [comment]
Please resolve the merge conflict. @yojibeans

**Review by Carl-Tabuso — APPROVED** [review]

**Pull request merged**
