### PR TITLE
feat: Added multiple new pages

### PR DESCRIPTION
**Pull request by yojibeans**
**New pages added**
- change-password.php
- edit-profile.php
- profile.php
- change-password.js
- profile.css
- Added directory for the change-password icons

**Issues yet to be covered**
- Page responsiveness
- The color of the profile information (ELITE Account logged in) seems to be the color of AECES. I'll leave the partner team or the developer of the admin dashboard to fix the color issue.
- Change Password modal
   - The submit button was kept enabled so that the developer could proceed to the change-password page. I'll leave it to the back-end team on how they will proceed with the logic behind it.
- In the change-password.php, the "Set Password" was enabled thinking that the back-end team would do something more logical there. **NOT WORKING THOUGH**

### CODE REVIEW

**Review by Carl-Tabuso — COMMENTED** [review]
Let's address the incorrect font colors of text on the sidebar and the footer not sticking to the bottom of the page on profile page. Also, the content body of your new added pages look clumsy due to left and right spacing of the container. See images

image

image

image

After addressing the issues above, we can proceed with the merging

**Comment by yojibeans** [comment]
The issue with regards with the footer adjusting is based on the contents of the body itself. So the smaller the contents in the body, it will automatically adjust.

**Comment by Carl-Tabuso** [comment]
> The issue with regards with the footer adjusting is based on the contents of the body itself. So the smaller the contents in the body, it will automatically adjust.

Then how can we make it stick to the bottom regardless of screen size? It's unpleasant to look at and definitely wrong.

**Comment by yojibeans** [comment]
I already talked to Biella with regards to this, she said they should issue it to her.
image

**Review by Carl-Tabuso — APPROVED** [review]
Will submit an issue ticket.

**Pull request merged**
