### PR TITLE
At3 154

### PR DESCRIPTION
**Pull request by make-sundae**
Quick fix

Bug
upon clicking set schedule button the validation will be called first
The issue is that this validation incorrectly sets the end date and time value to the value fetched from the server

Fix 
Remove this incorrect code of the client side validation

Additional notice discovered same day start and end schedule will be marked as invalid date

### CODE REVIEW

**Comment by make-sundae** [comment]
I also added small updates to configuration page header

**Comment by Carl-Tabuso** [comment]
Is the **All Day** feature yet to work? I have to specify the start and end time to insert into the election_schedule table.

**Comment by make-sundae** [comment]
> Is the **All Day** feature yet to work? I have to specify the start and end time to insert into the election_schedule table.

This what it do when the all day is toggled
I toggle the time to 
START 00:00 
to 
END 23:59

Then if untoggled I reset the time to what is initially fetched from the server

https://drive.google.com/file/d/1vkpQY2zivtB7f8-iNQJtMA8Oc7WGQzAQ/view?usp=sharing

https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/assets/92857477/7a141a20-52e6-4355-b4d9-1032ae35be5d

I request if you can elaborate the issue if this incorrect?

**Comment by Carl-Tabuso** [comment]
> This what it do when the all day is toggled I toggle the time to START 00:00 to END 23:59
> 
> Then if untoggled I reset the time to what is initially fetched from the server
> 
> https://drive.google.com/file/d/1vkpQY2zivtB7f8-iNQJtMA8Oc7WGQzAQ/view?usp=sharing
> 
>  localhost._.127.0.0.1._.db_acap._.election_schedule._.phpMyAdmin.5.2.1.-.Google.Chrome.2024-06-18.16-38-13_1.mp4 
> I request if you can elaborate the issue if this incorrect?


Does this mean I should have an initial row before setting it into All Day? I can't seem to debug the problem. Am I doing this wrong?

https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/assets/162773681/5231bb71-fc8e-4388-8e40-0d9844d783cc

**Comment by make-sundae** [comment]
> > This what it do when the all day is toggled I toggle the time to START 00:00 to END 23:59
> > Then if untoggled I reset the time to what is initially fetched from the server
> > https://drive.google.com/file/d/1vkpQY2zivtB7f8-iNQJtMA8Oc7WGQzAQ/view?usp=sharing
> > localhost._.127.0.0.1._.db_acap._.election_schedule._.phpMyAdmin.5.2.1.-.Google.Chrome.2024-06-18.16-38-13_1.mp4
> > I request if you can elaborate the issue if this incorrect?
> 
> Does this mean I should have an initial row before setting it into All Day? I can't seem to debug the problem. Am I doing this wrong?
> 
>  2024-06-18.17-30-12.mp4

I get it now its the condition in serverside that limits the minimum date

I think Ill adjust it to be able to set the until current date

**Comment by make-sundae** [comment]
After analyzing the issue the error START_TIME_IN_THEPAST is indeed invalid since you are setting start date today

setting all day thus set the time from start of time of this day is 12:00AM  
but today the 12:00 am has elapsed


should I let setting all day when the starting date is today?

**Comment by Carl-Tabuso** [comment]
> should I let setting all day when the starting date is today?

I think you should. It's not far-fetched that the user may do something like setting the starting date today. Despite that, your code does actually work just fine for **All Day** toggle if the starting date is not set today. Do work on the feedback message after setting the schedule.

**Review by Carl-Tabuso — APPROVED** [review]
Tested it on my end. It works just fine. You may proceed working with the success modal and edit schedule state.

**Pull request merged**
