### PR TITLE
Registration Form CAPTCHA

### PR DESCRIPTION
**Pull request by Carl-Tabuso**
# Feature

- Implemented Google reCAPTCHA v2 on the registration form to deter spam bots and abuse. 👇
```html
    <!-- Google reCAPTCHA API -->
    <script src="https://www.google.com/recaptcha/api.js" async defer></script>
```

> [!CAUTION]
> - GitGuardian is most likely to flag this due to the secret keys this branch contains.
> - For client-side validation it has a public key on `register.php` and the private/secret key for server-side validation is located in `includes/registration-inc.php`

### DEMO

https://github.com/user-attachments/assets/af8eecc0-fb89-47bf-bc5f-d1c4704265ce

> [!NOTE]
> Message me in our group chat if you need to access to the google recaptcha admin site.

### CODE REVIEW

**Comment by Carl-Tabuso** [comment]
UP [everyone?](https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/blob/development/.github/CODEOWNERS)

**Comment by make-sundae** [comment]
Is the middle name not saving?
https://drive.google.com/open?id=1eZVAjTBBNFi4lmT1v01l-smmk55TukOH&usp=drive_fs

The form can be submitted even expired recaptcha?
https://drive.google.com/open?id=1eZ2spmV4-O3XPZxNeRBYq3z1pzg0wlcg&usp=drive_fs

**Comment by Carl-Tabuso** [comment]
> Is the middle name not saving? https://drive.google.com/open?id=1eZVAjTBBNFi4lmT1v01l-smmk55TukOH&usp=drive_fs
> 
> The form can be submitted even expired recaptcha? https://drive.google.com/open?id=1eZ2spmV4-O3XPZxNeRBYq3z1pzg0wlcg&usp=drive_fs

I will try to reproduce them on my end and fix them asap.

**Comment by Carl-Tabuso** [comment]
UP @C-Ivan-Bandilla 

## Changes made:

- Corrected logical errors in the `registration-class.php`. It now checks if the middle or suffix name is empty before assigning NULL values.

Line 126:
```php
            // Assigns NULL to middle name if it's empty
            $this->middle_name = empty($this->middle_name) ? NULL : $this->middle_name;
```

Line 138:
```php
            // Assigns NULL to suffix name if it's empty
            $this->suffix = empty($this->suffix) ? NULL : $this->suffix;
```

- For client-side validation of expired captcha, I've added a final check  upon submitting the form [that cheks whether the recaptcha response is equal to zero—meaning it's either expired or not filled-in yet.

`register.js (Line: 515-528)`

```javascript
    const captchaToken = grecaptcha.getResponse();

    if (captchaToken.length === 0) {
      event.preventDefault();
      checkFormValidity();
      grecaptcha.reset();
    } else {
      // show button preloader
    }
```

**Review by make-sundae — APPROVED** [review]

**Pull request merged**
