### PR TITLE
Update configuration schedule

### PR DESCRIPTION
**Pull request by make-sundae**
Updates for the Configuration of the election schedule

### CODE REVIEW

**Comment by make-sundae** [comment]
Added  sending data to the server only 
Further progress shall be made on follow up commits

**Comment by make-sundae** [comment]
Removed unsafe jQuery plugin -> air datepicker v2 this shall resolve #163 
- [x] https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/security/code-scanning/1


/assign @C-Ivan-Bandilla #163

**Comment by Carl-Tabuso** [comment]
Can you give me an example recording of how the election scheduling supposed to work?

**Comment by make-sundae** [comment]
### Added feature schedule 

- Setting date
- limited validation message but is handled on server

### Not yet implemented

- time picker with similar style
- view state when schedule is already set
- edit state
- success modal

- csrf is only implemented in set schedule 
- csrf is not using the utility class

the table is used is the same on draft in
https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/pull/103#:~:text=Tentative%20table%20for%20schedule
```
CREATE TABLE IF NOT EXISTS `election_schedule` (
  `schedule_id` tinyint(3) UNSIGNED NOT NULL,
  `start` datetime NOT NULL,
  `close` datetime NOT NULL,
  PRIMARY KEY (`schedule_id`)
);
```
### Demo

https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/assets/92857477/36bdc06c-85b8-47d7-a79a-00fa166c13d7



https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/assets/92857477/5d216a85-3064-4fc2-bffd-b04972039477

**Comment by make-sundae** [comment]
Further features not yet implemented will not be included in this current pr

Next pr will cover unimplemented pages

**Review by Carl-Tabuso — APPROVED** [review]
No further comments.

**Pull request merged**
