### PR TITLE
feat: updates to voting schedule

### PR DESCRIPTION
**Pull request by make-sundae**
Added view state and edit state

### Known bugs
Icons on date and time on firefox
This was discovered a long time ago

But I want to disclose this

I wasn't able to style the built in input styles in firefox known as pseudo element of _shadow dom_

Shadow dom are elements that are hidden on normal settings this are the built in elements inserted by the browser here is an example 
image

https://www.reddit.com/r/FirefoxCSS/comments/rebn3s/cant_change_some_shadowdom_properties/
image

Will still add the mass mail functionality

### CODE REVIEW

**Comment by make-sundae** [comment]
What git guadrdian notified is my [smtp password](https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/commit/10e75207029a35dc7d874976b342371f3d3694c0#diff-7c014e330afeb8f6740ef0b23948f90e2f4ac56301328b1991f074c8c3118f83R36:~:text=%40%40%20%2D0%2C0%20%2B1%2C41%20%40%40-,%3C%3Fphp,return%20%24mail%3B,-77%20changes%3A%2075)

Added sending mass email when the datetime now is within the close schedule to those verified student
Using the test mail in order to not affect the reputation of the official email

Sometimes the email is delayed or blocked 
Maybe due to sending mass mail consecutively in previous days the reputation of my mail is low prio

will still try to fork this and test on hosting to test if the chron job will work

**Comment by make-sundae** [comment]
nevermind I wasn't able to test by creating a new website for there is unknown error or issue
https://drive.google.com/file/d/1szQmX0Iy5zaTo5fBx1JZIvEju_TH1LdQ/view?usp=sharing

will just address the issue that the script can be run only if has logged in session when SQL should be runnable  because the chronjob will automatically run the script without logging in

or find a method still there is authentication while using chron job

**Comment by make-sundae** [comment]
Table added

```
CREATE TABLE `email_queue` (
  `email_id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `schedule` datetime NOT NULL,
  `content` blob NOT NULL,
  `status` enum('pending','sent','failed') NOT NULL,
  `push_id` char(64) NOT NULL,
  PRIMARY KEY (`email_id`)
)
```


Modified voting_schedule_ able
```
ALTER TABLE election_schedule
ADD push_id char(64) NOT NULL AFTER close;
```

**Comment by make-sundae** [comment]
Email sample draft
image

**Comment by make-sundae** [comment]
This sending the email manually 
https://drive.google.com/file/d/1t1pR1ugc58mq0lMPI_bF1sJAF0053_3R/view?usp=sharing

NOTE _After running the chron job manually may set the org session to piie_

**Comment by Carl-Tabuso** [comment]
Is mass mailing running async in the background upon the closing of voting period, regardless if admin is logged in or not?

**Review by Carl-Tabuso — CHANGES_REQUESTED** [review]
I'm encountering a page reload upon adding a new candidate. This is due to a setTimeOut function you have in your javascript somewhere. It would be best to replace it with a toast so it won't be sort of disruptive that they have to click or close the modal and carry on with adding additional candidates and such.

https://github.com/user-attachments/assets/4f39af70-247f-4c5b-b75d-688a2e8f633d

**Comment by make-sundae** [comment]
My implementation is saving the mass mail data in database for later sending 

my initial plan is to have [PHP](https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/pull/264/files#:~:text=66%20changes%3A%2066,email%2Dqueue.php) script in cron job folder this PHP file checks if there is an email scheduled for now 
the scripts check emails on all orgs databases

this PHP will be run every one minute in cron job 

if there is scheduled email then the sending will happen automatically if it will work in hostinger

**Comment by Carl-Tabuso** [comment]
> My implementation is saving the mass mail data in database for later sending
> 
> my initial plan is to have [PHP](https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/pull/264/files#:~:text=66%20changes%3A%2066,email%2Dqueue.php) script in cron job folder this PHP file checks if there is an email scheduled for now the scripts check emails on all orgs databases
> 
> this PHP will be run every one minute in cron job
> 
> if there is scheduled email then the sending will happen automatically if it will work in hostinger

This mass mailing is an additional functionality/improvement added on top of the closed voting period notif UI to be implemented on login or landing page. And as such, it doesn't concern us much if a user hasn't received an email.

Have you tried this yet again on Hostinger if it's working? I remember in your previous comment that you encountered a problem about its implementation for there is an unknown error or issue.

**Comment by make-sundae** [comment]
> Have you tried this yet again on Hostinger if it's working? I remember in your previous comment that you encountered a problem about its implementation for there is an unknown error or issue.


Okay Ill try to make it work again

the problem that I mention there is I was trying to test it on hostinger on a separate website but I was unable to login here
https://olive-deer-977022.hostingersite.com/

UPDATE: I was able to login now
Maybe you fix db configuration ?

**Comment by Carl-Tabuso** [comment]
> the problem that I mention there is I was trying to test it on hostinger on a separate website but I was unable to login here
https://olive-deer-977022.hostingersite.com/

I'll check up on this.

**Comment by Carl-Tabuso** [comment]
I found the issue. Since upon clicking on an org card starts and sets your session,  you forgot to change the domain in `session-handler.php` specifically the domain parameters of `session_set_cookie_params()`. 

From 

image


To 

image

It works on my end now.

**Comment by make-sundae** [comment]
I was able to make it work however my script in this version is not applicable to hostinger 
 **_src/cron-jobs/send-email-queue.php_**

_from this github script_
image

_This from hostinger_
image
- This now doesn't rely on session superglobal

https://drive.google.com/file/d/1t3TiUF7DkcUMxf0d2oAp3e_wmr2ILI5c/view?usp=sharing
chron job is running every minute to check for pending email on all organization

**Comment by make-sundae** [comment]
Should the update on sending be addressed on next pr?
This pr only queue email for later sending

**Comment by Carl-Tabuso** [comment]
You choose. I think I can approve of this already. You may push all the changes here on mass mailing or address it on your next pr.

**Comment by make-sundae** [comment]
I'd like to address them on next  new pr and have an issue ticket for this if needed

**Comment by Carl-Tabuso** [comment]
Also, I think you're gonna have to do some workarounds on mass mailing because you're using a different credentials for smtp server, right?

**Comment by make-sundae** [comment]
> Also, I think you're gonna have to do some workarounds on mass mailing because you're using a different credentials for smtp server, right?

Yes, will delete the mailer-test for that and instead use mailer.php

**Review by Carl-Tabuso — APPROVED** [review]

**Comment by Carl-Tabuso** [comment]
I should remind myself that there's a newly added table here.

**Comment by make-sundae** [comment]
Here is the [
alter-voting-schedule.php](https://drive.google.com/file/d/1v6kNVqlL_aOKaryO-zri8jJsyNhbxehH/view?usp=drive_link)

[create-email-queue.php](https://drive.google.com/file/d/1DckB6CTNaOClK8v-mz6X9DkfpuJs92jC/view?usp=drive_link)

**Pull request merged**
