### PR TITLE
Added table for the candidate count by position

### LINKED ISSUE #146: Election Reports: Task List
Unresolved issues from PR #135

## Task List
- [x] #147
- [x] #148
- [x] #149
- [x] #150
- [x] #151

### LINKED ISSUE #150: ER: Page Responsiveness
Allow your page to accommodate the minimum screen resolution of 1280x1024.

Quoted from PR #135 
> Keep in mind the resolution of other screen sizes. I've tested it on mine — 1280x1024 and this looks unpleasant.
> 
> image
> 
> I had to zoom out to 80% to make it look as it was supposed to.

### LINKED ISSUE #259: ER: Comprehensive Election Data
1. Display the total number of candidates running for a certain position.
2. Provide detailed information about candidates running for a certain position.
3. Include 1 and 2 to the generated PDF/other files election reports.

### PR DESCRIPTION
**Pull request by Ivan-Edan**
**Description:** This PR is about the latest enhancements when it comes to the Election Reports Module.
**The Changes includes:**
- The table for the candidate count
- modal for each candidate count in position
- fix the bug on modal overlay in the feedback modal.
- added ajax on the feedback table.
- added the latest changes in the pdf for the winners and also pdf for overall.
- fix the loading when clicking the sorting dropdowns

Sample output: 
Screenshot (99)
Screenshot (100)
Screenshot (102)
Screenshot (103)
Screenshot (104)
(P.S ignore the actual picture and description in the modal it was that sample data when it comes to my database)

Closes #259 
Closes #150 
Closes #146

### CODE REVIEW

**Comment by Ivan-Edan** [comment]
Should I comment out temporary the mailer-test.php ?

**Comment by make-sundae** [comment]
> (P.S ignore the actual picture and description in the modal it was that sample data when it comes to my database)

image

the json part is the actual data
it can be processed to display
this pr can be a referenced

https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/pull/184#:~:text=Resource%20if%20needed%20https%3A//quilljs.com/docs/api%23editor

---
also I encountered an issue when there is no position, candidate and feedback available but the schedule closed


https://github.com/user-attachments/assets/ff543f87-966e-4a62-9c85-0ef03a3cb25a

it will load forever to be specific this only happen when feedback table has no data
image


this is for election reports

**Comment by Carl-Tabuso** [comment]
This is not even responsive on all screen sizes, especially to the smallest breakpoint in mobile devices. On candidate table and feedback section, you aren't supposed to be text-wrapping. This doesn't align with what's on our mockup UI — alignment of elements, layout, and sizes of close buttons. I don't also understand why some containers have borders and some don't.

Take a close look at this video

https://github.com/user-attachments/assets/39106ce6-f06e-48f7-be53-c620ec931282

<hr/>

> [!CAUTION]
> Please always check your error text file for error logs. The code block below is just one of the many errors I keep getting.

```
2024-07-17 12:09 pm Error: [2] Undefined variable $baseDir - C:\xampp\htdocs\PUPSRC-AutomatedElectionSystem\src\includes\result-candidates.php: 15
2024-07-17 12:09 pm Error: [2] include(\includes\session-exchange.php): Failed to open stream: No such file or directory - C:\xampp\htdocs\PUPSRC-AutomatedElectionSystem\src\includes\result-candidates.php: 15
```

**Comment by Ivan-Edan** [comment]
Will resolve this matter, thanks

**Comment by Ivan-Edan** [comment]
Already adjust the responsiveness and remove some border and text wrapping for the headers of the tables, for now is all the best I can do to remedy the situation, my apologies I hope you all can understand. Thanks

**Comment by make-sundae** [comment]
The loading still exist this happen only if feedback table has no data 

https://drive.google.com/open?id=1t9lUZffjshPMqsDvhSc1HGVWRAwuwyNx&usp=drive_fs

**Comment by AraojoBenedict** [comment]
> The loading still exist this happen only if feedback table has no data
> 
> https://drive.google.com/open?id=1t9lUZffjshPMqsDvhSc1HGVWRAwuwyNx&usp=drive_fs

image
added empty space in handling if feedback table has no data

**Comment by AraojoBenedict** [comment]
> > (P.S ignore the actual picture and description in the modal it was that sample data when it comes to my database)
> 
> image
> 
> the json part is the actual data it can be processed to display this pr can be a referenced
> 
> #184
> 
> also I encountered an issue when there is no position, candidate and feedback available but the schedule closed
> 
>  Election.Reports.-.Google.Chrome.2024-07-17.11-44-14.mp4 
> it will load forever to be specific this only happen when feedback table has no data image
> 
> this is for election reports

not used in utilizing quill from a json file. I opt on sticking fetching data from db. Here is the sample of displaying description from inputting the position description from the configuration module:

**Review by make-sundae — APPROVED** [review]
Major Bug is fixed that causing indefinite loading or 500 status code

Issues left to address for next pr

- Overflowing content on screen size less than 400
- Displaying of position roles on viewing all candidates in a position modal

https://drive.google.com/file/d/1tEpHt-HIxsMt6OkANj74zNOFE6nMP8x9/view?usp=sharing

**Pull request merged**
