### PR TITLE
feat: AT1-203 apply initial configurations to reflect in the ballot form page

### PR DESCRIPTION
**Pull request by Andrea-Villalobos**
Details:

https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/assets/162780943/837153ba-2956-4f2f-a988-7108f66797ec

- Applied the sequence of positions

- Display the text attributes from the description (e.g. the text is bold)
Screenshot 2024-06-25 230848

- Applied the max_votes
- Changed the radio button to check boxes due to instances of multiple selections of candidates per position
- Modified the validation code since it was changed to checkboxes
- Same with the insert-vote.php
- Once the abstain is selected, the selected candidates is automatically removed.
- Improved the responsiveness of ballot forms
Screenshot 2024-06-25 230312

style: minor modification in other pages
- display icons in the feedback-suggestions.php in the top nav bar
- adjust text weight in the end point

Will further improve to follow what is on the figma

Concerns:
To which table will the data from the name and student number be stored?
What image placeholder can I use for the abstain?
Screenshot 2024-06-25 231324

Thank you.

Apologies, I forgot to follow the correct naming of branch.

### CODE REVIEW

**Comment by Carl-Tabuso** [comment]
Assigning the code review to @C-Ivan-Bandilla.

**Comment by make-sundae** [comment]
It's okay for me
Disregard the text background color


Issues that could be addressed in the next commits are

- [ ] 1.  Representation of ordered and unordered list
- [ ] 2.  Combination of styles applied to text

[Proof of Testing](https://drive.google.com/file/d/1rmgVpbUJFttsgJxh-Q3EllBfy1HIEVgO/view?usp=sharing)




Others that can be improve

I acknowledge that you mentioned how to change vote
If it is what is instructed to do you can disregard this
- To be able to change a vote requires selecting abstain first, if possible it can be easier to change vote selection
___
Resource if needed [https://quilljs.com/docs/api#editor](https://quilljs.com/docs/api#editor)

You can merge changes once your queries are addressed.


> To which table will the data from the name and student number be stored?
> What image placeholder can I use for the abstain?

**Review by make-sundae — APPROVED** [review]

**Comment by Carl-Tabuso** [comment]
> Concerns:
 To which table will the data from the name and student number be stored?

I have asked Yuri if there is a significance collecting such informations. I'll get back to you soon.

> What image placeholder can I use for the abstain?

About this, you may ask @biellamariscotes

**Comment by Carl-Tabuso** [comment]
Update on:
> I have asked Yuri if there is a significance collecting such informations. I'll get back to you soon.

@Andrea-Villalobos  I've asked other leads about the collection of student's personal information on ballot forms. It was decided that it will be removed.

1. Ballot Forms should not collect any personal information, focusing only on the actual casting of votes.
2. For ballot forms configuration handled by Ivan Bandilla, he had been informed that such functionalities will be completely removed.

You decide whether to merge or close this PR and work on the removal of Name and Student Number fields on your next. We're sorry for the inconvenience this has caused.

**Comment by Andrea-Villalobos** [comment]
> Update on:
> 
> > I have asked Yuri if there is a significance collecting such informations. I'll get back to you soon.
> 
> @Andrea-Villalobos I've asked other leads about the collection of student's personal information on ballot forms. It was decided that it will be removed.
> 
> 1. Ballot Forms should not collect any personal information, focusing only on the actual casting of votes.
> 2. For ballot forms configuration handled by Ivan Bandilla, he had been informed that such functionalities will be completely removed.
> 
> You decide whether to merge or close this PR and work on the removal of Name and Student Number fields on your next. We're sorry for the inconvenience this has caused.

This is noted. Currently working on this and fixing the display of the duties and responsibilities modal and will be pushing a commit within this day. Thank you.

**Comment by Andrea-Villalobos** [comment]
- Removed the student information fields

https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/assets/162780943/fabdad1a-41c6-4fe2-8093-3734e561fe1c

- Fixed the display of the content in the duties and responsibilities

Screenshot 2024-06-28 134048

Kindly review again. Thank you.

**Comment by Carl-Tabuso** [comment]
> Kindly review again. Thank you.

UP @C-Ivan-Bandilla

**Pull request merged**
