### PR TITLE
Adding sorting function in descending order to candidates position and session of organization

### PR DESCRIPTION
**Pull request by Ivan-Edan**
**Overview**
This PR is all about adding a sorting function in descending order to candidates positions and session of organization in result generation module.

**Changes Added**
- sorting function that makes the candidate with the highest vote appear at the top with a matching color border.
- Added session to an organization that changes color depending on the log-in organization
- Adjust padding in candidate's container
- Added automatic to uppercase in some text like student name and "for position"
- slightly added responsiveness in some areas.

**Addition Notes**
- Need to improve the responsiveness

**Example Output**
image

### CODE REVIEW

**Review by Andrei-Matibag — APPROVED** [review]
review approved

**Review by Carl-Tabuso — CHANGES_REQUESTED** [review]
Use file utility class for path normalization and consistency. See images below.

image
image

**Comment by Ivan-Edan** [comment]
The requested changes have already been modified. Below is the code that was use.
image

**Comment by Ivan-Edan** [comment]
Some of the changes has been edited:
image

Some example of responsiveness from devices:
image
image
image

**Notes to remember** 
The responsiveness of this module can be enhanced in future updates or requests.

**Review by Carl-Tabuso — COMMENTED** [review]
The readability of your codes has improved. Before we proceed with the merging, please address this concern about the positioning of texts on the reports page. They are not properly placed in the middle. Additionally, the placeholder when "No position available" looks clumsy. Take a look at the image below. 

image

**Review by Carl-Tabuso — APPROVED** [review]

**Comment by Ivan-Edan** [comment]
Here is the changes that was requested:
image
image

**Pull request merged**
