### PR TITLE
feat: added the emailing of start end close of election

### PR DESCRIPTION
**Pull request by make-sundae**
Used the official email on mailing
Refactored usage of variables due to conflicting of values of inclusion of logger.php
      which requires the session-exchange.php that already has the organization-list.php

Added activity logging on
- setting voting schedule
- updating voting schedule

Already deleted the mailer-test.php and updated the gitignore file
image

### CODE REVIEW

**Comment by make-sundae** [comment]
Working  on demo Still finding the issue that
I can run the email sender manually and sends email okay

But the cron job in hostinger is not executing the PHP properly even no error run output

**Comment by make-sundae** [comment]
Finally it worked!

https://drive.google.com/open?id=1tEOQd3cx-9pFpVEAWKHifz9I62PRhTF_&usp=drive_fs

here is the correct email should have been scrolled down to see the latest email I thought it also had the incorrect time
image


fix the include and require conflict found on https://olive-deer-977022.hostingersite.com/

Issue overview
The sending of mass mail manually has no issue but when it is run from cron job there is a hidden error
The issue is within inclusion of session-exchange.php that is included in email-sender.php
The session-exchange.php contains the session-handler.php that causes this error

2024-07-19 5:21 pm Error: [2] ini_set(): Session ini settings cannot be changed after headers have already been sent - /home/u155023598/domains/olive-deer-977022.hostingersite.com/public_html/src/includes/session-handler.php: 6
2024-07-19 5:21 pm Error: [2] ini_set(): Session ini settings cannot be changed after headers have already been sent - /home/u155023598/domains/olive-deer-977022.hostingersite.com/public_html/src/includes/session-handler.php: 7
2024-07-19 5:21 pm Error: [2] session_set_cookie_params(): Session cookie parameters cannot be changed after headers have already been sent - /home/u155023598/domains/olive-deer-977022.hostingersite.com/public_html/src/includes/session-handler.php: 10
2024-07-19 5:21 pm Error: [2] session_start(): Session cannot be started after headers have already been sent - /home/u155023598/domains/olive-deer-977022.hostingersite.com/public_html/src/includes/session-handler.php: 17
2024-07-19 5:21 pm Error: [2] Cannot modify header information - headers already sent by (output started at /home/u155023598/domains/olive-deer-977022.hostingersite.com/public_html/src/cron-jobs/send-email-queue.php:10) - /home/u155023598/domains/olive-deer-977022.hostingersite.com/public_html/src/includes/session-exchange.php: 8

- Applied the fix made on https://olive-deer-977022.hostingersite.com/ which caused issue on sending mass emails on cron job execution
by removing session-exchange.php in email-sender.php

**Comment by make-sundae** [comment]
Upon approval and confirmation that mass emailling is working this issue shall be close #282

**Comment by Carl-Tabuso** [comment]
@biellamariscotes UP

**Comment by Carl-Tabuso** [comment]
It seems that you've managed to make it work, if so, you think we can merge this?

**Comment by make-sundae** [comment]
> It seems that you've managed to make it work, if so, you think we can merge this?

Yes, it can be 

 I already setup also the cron job for ivote it can be tested further once updated
 
 NOTE: if more than 98 verified voters in table they will be divided into 98 per batch with 30mins interval each

**Review by Carl-Tabuso — APPROVED** [review]

**Pull request merged**
