### PR TITLE
feat: initial commit for recycle-bin

### PR DESCRIPTION
**Pull request by Peter-Escueta**
**REQUIRED ADDITIONS TO THE DATABASE**
Considering the addition of Candidates in the recycle-bin.php it is requested to have the following:
status_updated TIMESTAMP current_timestamp()
register_date TIMESTAMP current_timestamp()
candidacy_status(debatable values but i used added or removed)
removal of candidate foreign key on "vote" database table ( I suggest removing foreign keys for both position_id and candidate_id and simply taking the values so as to not require to delete votes before you can delete a position or candidate unless votes must be deleted.)
**Up For Discussion**
Event Trigger for MySQL to DELETE FROM voter WHERE account_status = "invalid" AND status_updated < NOW() - INTERVAL 30 DAY

Currently Functioning:
All modals ( Still has UI inaccuracies)
All Table Functionality( Sort, Delete, Restore, Search and Pagination)
Responsivity

Known Issues:
Select All quite literally selects all ( does not select with regards to rows per page)
UI Discrepancies like translation of values ( head_admin to Head Admin, 2024-06-03 to June 3, 2024)
Modal Height to 50%

### CODE REVIEW

**Comment by Carl-Tabuso** [comment]
> **REQUIRED ADDITIONS TO THE DATABASE** Considering the addition of Candidates in the recycle-bin.php it is requested to have the following: 
status_updated TIMESTAMP current_timestamp() 
register_date TIMESTAMP current_timestamp() 
candidacy_status(debatable values but i used added or removed) 
removal of candidate foreign key on "vote" database table ( I suggest removing foreign keys for both position_id and candidate_id and simply taking the values so as to not require to delete votes before you can delete a position or candidate unless votes must be deleted.) 

I've been talking with @C-Ivan-Bandilla from PR #103 about the deletion of the `position_id` field in the `vote` table because we deemed it unnecessary and may cause an issue in the long run. But for the `candidate_id`, instead of deleting the foreign key, you perhaps mean to change its constraints?

> **Up For Discussion** Event Trigger for MySQL to DELETE FROM voter WHERE account_status = "invalid" AND status_updated < NOW() - INTERVAL 30 DAY

For triggers, you can talk about them with @biellamariscotes. She said to me yesterday that she'll handle the additions of triggers in our tables. Seek her approval.

**We shall have a meeting again with everyone to communicate the desired and made changes in our database.**

**Review by Carl-Tabuso — COMMENTED** [review]
## Unnecessary File
You may remove the `session-manager.php` file. Its usage scope is only for pages that don't set the voter_id session of a user, such as landing, login, registration page, and more.

```php
require_once FileUtils::normalizeFilePath('includes/classes/session-manager.php');
```

Files that contain such:

1. `recycle-bin.php`
2. `recycle-bin-candidate.php`
3. `recycle-bin-admin.php`
4. `delete-selected-candidates.php`
5. `delete-selected-voter.php`
6. `recycle-bin-admin-modal.php`
7. `recycle-bin-modal.php`
8. `restore-selected-candidate.php`
9. `restore-selected-voter.php`

## HTML Codes

1. (All files) Please indent your HTML codes properly. I don't which opening div is pointing to which closing div.

image

## Insecure SQL

1. I found several files in `submission_handlers.php` where SQL query parameters don't use prepared statements.
2. The use of prepared statements is not only to avoid SQL injection but also to maintain consistency with other queries.

Files:

1. `submission_handlers/recycle-bin-admin.php`
2. `submission_handlers/recycle-bin-candidate.php`
3. `submission_handlers/recycle-bin-committee.php`
4. `submission_handlers/recycle-bin.php`

My review and comments are code-level. I'd leave it to @biellamariscotes to test the recycle bin UI.

**Comment by Peter-Escueta** [comment]
> > **REQUIRED ADDITIONS TO THE DATABASE** Considering the addition of Candidates in the recycle-bin.php it is requested to have the following: 
> status_updated TIMESTAMP current_timestamp() 
> register_date TIMESTAMP current_timestamp() 
> candidacy_status(debatable values but i used added or removed) 
> removal of candidate foreign key on "vote" database table ( I suggest removing foreign keys for both position_id and candidate_id and simply taking the values so as to not require to delete votes before you can delete a position or candidate unless votes must be deleted.) 
> 
> I've been talking with @C-Ivan-Bandilla from PR #103 about the deletion of the `position_id` field in the `vote` table because we deemed it unnecessary and may cause an issue in the long run. But for the `candidate_id`, instead of deleting the foreign key, you perhaps mean to change its constraints?
> 
> > **Up For Discussion** Event Trigger for MySQL to DELETE FROM voter WHERE account_status = "invalid" AND status_updated < NOW() - INTERVAL 30 DAY
> 
> For triggers, you can talk about them with @biellamariscotes. She said to me yesterday that she'll handle the additions of triggers in our tables. Seek her approval.
> 
> **We shall have a meeting again with everyone to communicate the desired and made changes in our database.**

indeed, I meant the deletion of the constraint not the column

**Comment by Peter-Escueta** [comment]
> ## Unnecessary File

Noted on this, i've done a commit to fix the stated issues, if the following changes are insufficient please do comment once again.

**Comment by Carl-Tabuso** [comment]
I'm getting this errors and I don't know why.

`recycle-bin.php`
```
2024-06-09 2:31 pm Error: [8192] Creation of dynamic property QueryExecutor::$status is deprecated - C:\xampp\htdocs\PUPSRC-AutomatedElectionSystem\src\submission_handlers\recycle-bin.php: 8
2024-06-09 2:31 pm Error: [8192] Creation of dynamic property QueryExecutor::$role is deprecated - C:\xampp\htdocs\PUPSRC-AutomatedElectionSystem\src\submission_handlers\recycle-bin.php: 9
``` 

`recycle-bin-candidate.php`
```
2024-06-09 2:31 pm Error: [8192] Creation of dynamic property QueryExecutor::$candidacy_status is deprecated - C:\xampp\htdocs\PUPSRC-AutomatedElectionSystem\src\submission_handlers\recycle-bin-candidate.php: 8
```

`recycle-bin-admin.php`
```
2024-06-09 2:31 pm Error: [8192] Creation of dynamic property QueryExecutor::$role is deprecated - C:\xampp\htdocs\PUPSRC-AutomatedElectionSystem\src\submission_handlers\recycle-bin-admin.php: 8
2024-06-09 2:31 pm Error: [8192] Creation of dynamic property QueryExecutor::$account_status is deprecated - C:\xampp\htdocs\PUPSRC-AutomatedElectionSystem\src\submission_handlers\recycle-bin-admin.php: 9
```


https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/assets/162773681/247d9406-3396-4b83-9735-1f7f06b46ad8

**Comment by Carl-Tabuso** [comment]
## Voter Accounts
1. The actual permanent deletion of account/s occur only upon closing the success modal

https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/assets/162773681/1b676155-81bf-47f1-93d8-c32db97bc43f


2. Same with permanent deletion, the restoration of account/s occur only upon closing the success modal.

https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/assets/162773681/32199d86-b7ed-4fdb-9833-73b1877d7d9e


3. No indicator or feedback if there is no available data in the table corresponding to the search made.

image


## Candidate 
1. I don't know if the issues with Voter Accounts can also be seen here—I don't have sample data on my end.
2. One issue we have is perhaps something related to the broken UI. If you can see the screenshot below, there is a text written on the upper left side of the screen saying "No accounts deleted." I'm not quite sure if this behavior can also be noticed in Voter Accounts.

image

### Question:
1. How is the "Candidates" recycle bin supposed to work? And if it's working, can you provide a sample demonstration?
2. Do you want to proceed with merging this pull request—to assign you a new issue ticket—specifically a task list?

**Comment by Peter-Escueta** [comment]
> ## Voter Accounts
> 1. The actual permanent deletion of account/s occur only upon closing the success modal
> 
>  2024-06-10.21-10-24.mp4 
> 2. Same with permanent deletion, the restoration of account/s occur only upon closing the success modal.
> 
>  2024-06-10.21-13-18.mp4 
> 3. No indicator or feedback if there is no available data in the table corresponding to the search made.
> 
> image
> 
> ## Candidate
> 1. I don't know if the issues with Voter Accounts can also be seen here—I don't have sample data on my end.
> 2. One issue we have is perhaps something related to the broken UI. If you can see the screenshot below, there is a text written on the upper left side of the screen saying "No accounts deleted." I'm not quite sure if this behavior can also be noticed in Voter Accounts.
> 
> image
> 
> ### Question:
> 1. How is the "Candidates" recycle bin supposed to work? And if it's working, can you provide a sample demonstration?
> 2. Do you want to proceed with merging this pull request—to assign you a new issue ticket—specifically a task list?

A commit will be done to add the following changes, in terms of how the candidate recycle bin should work, here's a sample demonstration following the UI schematics:

https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/assets/135005160/2d982c2f-3250-4c50-abd6-ecbd3a2aa1f9

**Review by Carl-Tabuso — APPROVED** [review]
Looks good to me.

**Comment by Carl-Tabuso** [comment]
I found this minor issue. Do fix this.

```
2024-06-11 10:12 pm Error: [2] include(includes\session-exchange.php): Failed to open stream: No such file or directory - C:\xampp\htdocs\PUPSRC-AutomatedElectionSystem\src\submission_handlers\recycle-bin-candidate-modal.php: 8
2024-06-11 10:12 pm Error: [2] include(): Failed opening 'includes\session-exchange.php' for inclusion (include_path='C:\xampp\php\PEAR') - C:\xampp\htdocs\PUPSRC-AutomatedElectionSystem\src\submission_handlers\recycle-bin-candidate-modal.php: 8
2024-06-11 10:12 pm Error: [2] include(includes\session-exchange.php): Failed to open stream: No such file or directory - C:\xampp\htdocs\PUPSRC-AutomatedElectionSystem\src\submission_handlers\recycle-bin-candidate-modal.php: 8
2024-06-11 10:12 pm Error: [2] include(): Failed opening 'includes\session-exchange.php' for inclusion (include_path='C:\xampp\php\PEAR') - C:\xampp\htdocs\PUPSRC-AutomatedElectionSystem\src\submission_handlers\recycle-bin-candidate-modal.php: 8
```

**Pull request merged**
