### PR TITLE
Updating config module

### PR DESCRIPTION
**Pull request by make-sundae**
### Added adding of election schedule
- Only the adding is still functional
- The list of values to be added is based on year and section available in voters table that is not existing to election_schedule table
- Styles are not well implemented
- Error prompt is not displayed

- [x] search icon placement on mobile should be fix

https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/assets/92857477/fd655e4c-c8bb-4f22-b11e-b9ab89f85a56

### CODE REVIEW

**Comment by C-Ivan-Bandilla** [comment]
|   |   |   |   |   |
|---|---|---|---|---|
|   |   |   |   |   |
|   |   |   |   |   |
|   |   |   |   |   |

**Comment by make-sundae** [comment]
### New Tables
Adding tables can be executed with [shed_date_year.php](https://drive.google.com/file/d/1QPUnmcxrQ96hX_IZ0G1WuVEFA1wtDtms/view?usp=sharing) for testing

- Election Year


|  Database Element | Type  | 
|---|---|
| election_id  | smallint(6)  |
|   year | year(4)  |
| is_current_year  | tinyint(1) as boolean  |

- Election Schedule

|  Database Element | Type  |   |
|---|---|---|
|  schedule_id |  mediumint(9) |  pk |
|  year_level | enum('1', '2', '3', '4', '5') | unique  |
|  section |  enum('1', '2', '3', '4') |  unique |
| schedule |  date |   |

I also added a constraint that year_level and section combination are unique

**Comment by make-sundae** [comment]
### Candidate Position
Added packages are for saving javascript logs to file but are commented out
Still finding the root cause of occasional description data corruption 

- [x] selection border style should be fix

https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/assets/92857477/e20d515c-71a6-4cf2-a21e-2315170716e0

**Comment by Carl-Tabuso** [comment]
I think I should ask other lead roles how we will go about with the scheduling of specific sections and year levels. The problem I see here is that we do not actually collect these information.

**Comment by Carl-Tabuso** [comment]
The "Enter a candidate position" placeholder shows upon clicking "ADD NEW POSITION" and then clicking on Cancel button. This perhaps is due to your javascript file `config-candidate-position.js`

image


Proof of Testing:

image

Also, the constraints for deletion of a position depends if there is a candidate running for that position in the `candidate` table. Consider this:

Candidate 1 is running for Treasurer (position id of 3). The candidate table in phpmyadmin looks something like this
| candidate_id| candidate_name | position_id (fk) |
|--------|--------|--------|
| 1 | candidate_1| 3 |

Due to this, we cannot delete the position on configuration page, no matter how much we click on  the Delete button. The problem is the lack of feedback messages. We can use alert messages or bootstrap toast in this case.

**Comment by Carl-Tabuso** [comment]
Is there any changes in the database?

**Comment by make-sundae** [comment]
> Is there any changes in the database?

Yes ,will add the update soon or if requested
The change is adding col max_votes for number of votes per positions 
```
ALTER TABLE `position`
ADD COLUMN `max_votes` tinyint(3) UNSIGNED NOT NULL DEFAULT 1
AFTER `title`;
```


Will that also need a breaking change commit?

Proper deletion of candidates and votes still in progress.

**Comment by Carl-Tabuso** [comment]
> > Is there any changes in the database?
> 
> Yes ,will add the update soon or if requested The change is adding col max_votes for number of votes per positions
> 
> ```
> ALTER TABLE `position`
> ADD COLUMN `max_votes` tinyint(3) UNSIGNED NOT NULL DEFAULT 1
> AFTER `title`;
> ```
> 
> Will that also need a breaking change commit?
> 
> Proper deletion of candidates and votes still in progress.

There's no need for a breaking change as it doesn't affect any API calls in our codebase. May I ask what is the purpose of the new field: `max_column` in position table?

Also, will you remove/change the `election_schedule` and `election_year`?

PS. Make sure your head branch is updated with the development.

**Comment by make-sundae** [comment]
> 
> There's no need for a breaking change as it doesn't affect any API calls in our codebase. May I ask what is the purpose of the new field: `max_column` in position table?
> 
> Also, will you remove/change the `election_schedule` and `election_year`?
> 
> PS. Make sure your head branch is updated with the development.

I noticed there is a change on UI although unclear, I assume that the purpose is some positions may require or have additional vote selection

image

I have not updated election year and election schedule yet will remove soon.

Noted, I'll update my feature branch

**Comment by Carl-Tabuso** [comment]
> > There's no need for a breaking change as it doesn't affect any API calls in our codebase. May I ask what is the purpose of the new field: `max_column` in position table?
> > Also, will you remove/change the `election_schedule` and `election_year`?
> > PS. Make sure your head branch is updated with the development.
> 
> I noticed there is a change on UI although unclear, I assume that the purpose is some positions may require or have additional vote selection
> 
> image
> 
> I have not updated election year and election schedule yet will remove soon.
> 
> Noted, I'll update my feature branch
> 
> I have asked Yuri about the vote selection. I'll relay the information promptly to the team once answered. Please provide a PHP file everyone can execute to add the `max_votes` field in the position` table and adjust/modify the create-tbl-sql accordingly in our google drive. Also update this branch, and then we will proceed with the merging. Thank you.

**Comment by Carl-Tabuso** [comment]
> > There's no need for a breaking change as it doesn't affect any API calls in our codebase. May I ask what is the purpose of the new field: `max_column` in position table?
> > Also, will you remove/change the `election_schedule` and `election_year`?
> > PS. Make sure your head branch is updated with the development.
> 
> I noticed there is a change on UI although unclear, I assume that the purpose is some positions may require or have additional vote selection
> 
> image
> 
> I have not updated election year and election schedule yet will remove soon.
> 
> Noted, I'll update my feature branch

 I have asked Yuri about the vote selection. I'll relay the information promptly to the team once answered. Please provide a PHP file everyone can execute to add the `max_votes` field in the position` table and adjust/modify the create-tbl-sql accordingly in our google drive. Also update this branch, and then we will proceed with the merging. Thank you.

**Comment by Carl-Tabuso** [comment]
## UPDATE

image

**Comment by Carl-Tabuso** [comment]
Mention me if this is ready for review and inform me what to test and remaining tasks/issues—We can assign you a new issue ticket. Thank you.

**Comment by make-sundae** [comment]
### Fixed adding blank row immediately in position list even if new position is not yet saved.


Root Cause

image

image


Remediation
insert position will be called only after getting a success response from server

```
if (success) {
      if (ConfigPage.mode === 'add') {
          ConfigPage.insertPosition(data);
      } else if (ConfigPage.mode === 'update') {
          ConfigPage.updatePostion(data);
      }

      ConfigPage.edit_position_modal.hide();
  }

insertPosition: function (DATA, draw = false) {

        if (DATA && DATA.data && Array.isArray(DATA.data)) {
            DATA.data.forEach(item => {
                console.log("each pos update " + JSON.stringify(item));
                let { sequence, data_id, input_id, value, max_votes, description } = item;
                if (!draw) {
                    let rowData = {
                        0: sequence,
                        1: {
                            data_id: data_id,
                            sequence: sequence,
                            value: value,
                            max_votes: (Number.isInteger(max_votes) && max_votes !== null) ? max_votes : 1
                        },
                        2: description
                    }

                    ConfigPage.table.row.add(rowData).draw(false);

                }
```


> The "Enter a candidate position" placeholder shows upon clicking "ADD NEW POSITION" and then clicking on Cancel button. This perhaps is due to your javascript file `config-candidate-position.js`
> 
> image
> 
> Proof of Testing:
> 
> image

___

### Fixed deletion of position even there is existing candidate

_Note: When there is a vote linked to a candidate but has a mismatch of position declared in candidate table
          position will not be deleted and server will respond an error status code
          but has no prompt for user_


> 
> Also, the constraints for deletion of a position depends if there is a candidate running for that position in the `candidate` table. Consider this:
> 
> Candidate 1 is running for Treasurer (position id of 3). The candidate table in phpmyadmin looks something like this
> 
> candidate_id	candidate_name	position_id (fk)
> 1	candidate_1	3
> Due to this, we cannot delete the position on configuration page, no matter how much we click on the Delete button. The problem is the lack of feedback messages. We can use alert messages or bootstrap toast in this case.

**Example**

| candidate | pos id |
| --------- | ------ |
| 1         | 1      |
| 2         | 1      |
| 3         | 2      |

| vote | candidate id | pos id         |
| ---- | ------------ | -------------- |
| 1    | 1            | 2 (mismatched) |
| 2    | 2            | 1              |
| 3    | 3            | 2              |
| 4    | 3            | 2              |

**Test Data**
position_test_data      [gzip](https://github.com/user-attachments/files/15524394/position_test_data.sql.gz)      [zip](https://github.com/user-attachments/files/15524393/position_test_data.sql.zip)

[Position.mp4](https://drive.google.com/file/d/1rGGDv167upbLIHXpaygdnTbFRnjb6cdC/view?usp=sharing)

___

```
CREATE TABLE IF NOT EXISTS `position` (
  `position_id` INT AUTO_INCREMENT NOT NULL,
  `sequence` INT UNSIGNED NOT NULL,
  `title` VARCHAR(50) NOT NULL,
  `max_votes` tinyint(3) UNSIGNED NOT NULL DEFAULT 1,
  `description` text,
  PRIMARY KEY (`position_id`)
);
```

Realized that I may have to match the position_id datatype
```
ALTER TABLE `position`
MODIFY `sequence` INT UNSIGNED NOT NULL;
```

Added a new column to allow position with multiple votes allowed
```
ALTER TABLE `position`
ADD COLUMN `max_votes` TINYINT(3) UNSIGNED NOT NULL DEFAULT 1
AFTER `title`;
```

**Tentative table for schedule** 
IF schedule change will be done on update queries
IF the approach should be adding row each time the schedule s modified a different structure may be needed

```
CREATE TABLE IF NOT EXISTS `election_schedule` (
  `schedule_id` tinyint(3) UNSIGNED NOT NULL,
  `start` datetime NOT NULL,
  `close` datetime NOT NULL,
  PRIMARY KEY (`schedule_id`)
);
```

**Comment by make-sundae** [comment]
> Mention me if this is ready for review and inform me what to test and remaining tasks/issues—We can assign you a new issue ticket. Thank you.

@Carl-Tabuso 
Addressed Blank Position on Adding then cancelling
Addressed Deleting Positions with constraints **but discovered an issue when vote data has an issue where vote table has mismatch data with candidate and position when I accidentally inserted SQL incorrectly on phpmyadmin**

**Comment by Carl-Tabuso** [comment]
## Acknowledged

1. > Fixed adding blank row immediately in position list even if new position is not yet saved.

## Concerns

I did see the issue when there is a mismatch of **position_id** in the `vote` table with the actual **position_id** the candidate is running for in the `candidate` table. 

We should perhaps remove the **position_id** in the `vote` table since we already have it in the `candidate` table referencing the `position` table. Therefore the **candidate_id** in the `vote` table will just have to join to the `position` table, if that makes sense.

What does the "Go to" button do?

image

**Comment by make-sundae** [comment]
> 
> What does the "Go to" button do?
> 
> image

This will be a link to view manage candidate page? if it is okay
but the page is not available on my end currently

**Comment by make-sundae** [comment]
> I did see the issue when there is a mismatch of **position_id** in the `vote` table with the actual **position_id** the candidate is running for in the `candidate` table.
> 
> We should perhaps remove the **position_id** in the `vote` table since we already have it in the `candidate` table referencing the `position` table. Therefore the **candidate_id** in the `vote` table will just have to join to the `position` table, if that makes sense.


If that's  the case I should revise deletion of votes part which should reference by candidate_id instead first

**Comment by Carl-Tabuso** [comment]
> > What does the "Go to" button do?
> > image
> 
> This will be a link to view manage candidate page? if it is okay

That's fine with me, but did the ui team know about this additional button? We can update your base branch and merge if you have no further changes to push on this pull request. What d u think?

**Comment by make-sundae** [comment]
> That's fine with me, but did the ui team know about this additional button? We can update your base branch and merge if you have no further changes to push on this pull request. What d u think?

Not yet informed.
It can be removed if unwanted since go to button is a draft and no function yet


I have no further changes to push in this current pr
will update the branch now
 Im not currently using the rebase as previously I encountered merge conflict when doing rebase

**Review by Carl-Tabuso — APPROVED** [review]

**Comment by make-sundae** [comment]
Is it okay too if have these changes merge to testing branch such that my qa will be able to test

**Comment by make-sundae** [comment]
> ALTER TABLE `position`
> MODIFY `sequence` INT UNSIGNED NOT NULL;

> ALTER TABLE `position`
> ADD COLUMN `max_votes` TINYINT(3) UNSIGNED NOT NULL DEFAULT 1
> AFTER `title`;

Modify position table can be run on 
[alter-position.php](https://drive.google.com/file/d/12M-xSG6Bwuy8Pk6bfVXK2OiI1eJzxaQW/view?usp=sharing)

___


_Current progress doesn't require this since back end  is still undeveloped and is also a draft_
> CREATE TABLE IF NOT EXISTS `election_schedule` (
>   `schedule_id` tinyint(3) UNSIGNED NOT NULL,
>   `start` datetime NOT NULL,
>   `close` datetime NOT NULL,
>   PRIMARY KEY (`schedule_id`)
> );

Add new table election schedule can be run on
[create-election-schedule.php](https://drive.google.com/file/d/1QPUnmcxrQ96hX_IZ0G1WuVEFA1wtDtms/view?usp=sharing)

**Pull request merged**
