### PR TITLE
chore: updates to updated UI in candidate position

### PR DESCRIPTION
**Pull request by make-sundae**
Added the view  and edit on candidate position

### CODE REVIEW

**Comment by make-sundae** [comment]
Still working adding confirm delete modal

**Comment by Carl-Tabuso** [comment]
Do comment if this is ready for review. Thanks

**Comment by make-sundae** [comment]
Screenshot 2024-07-12 200930
Confirm Delete

Screenshot 2024-07-12 201011
Confirm Delete on deletion conflict

https://drive.google.com/file/d/1sxjK4beko0L9OWBEKBObjwMB6L7GAX6f/view?usp=sharing


Added some client validation functions on roles and responsibilities

- No repeating character
- maximum of 1000 character

ready for reviewing

**Comment by Carl-Tabuso** [comment]
For the Confirm Delete modal, maybe you should use a combination of on input and change event here. What i noticed is that a user has to click away from the input field for the Delete button to enable.

image

<hr/>

There's no client feedback to the user if i were to click on the Save button with empty values

image

<hr/>

Let say i have one for the position name, you should perhaps add a red border as an indicator for Vote Selection

image

<hr/>
There was a time sir owen accessed the configuration page as a part of testing the live version on hostinger, he suggested that the "Add New Position" and in all config pages, the cursor should be the pointer one. He said that it was kinda misleading to use the cross cursor and it seems like you were taking a screenshot or snippet of your screen.

image


<hr/>

For the cancel button, can you add perhaps a border or anything that would make it appear more like button not a label.

image

<hr/>

I am wondering whether we should add some sort of tooltips and notes on how to use configuration. I'm quite sure this page isn't very intuitive to users and would sure need a lot of guidance to navigate their way through. Let's say something like.

Note: Double click on a position to edit it.

Something like that.

**Comment by Carl-Tabuso** [comment]
You decide whether we merge these changes along with a 'need issue ticket' label.

**Comment by make-sundae** [comment]
I'd like to have an issue ticket for the concerns thank you.

**Review by Carl-Tabuso — APPROVED** [review]
Will be assign an issue ticket.

**Pull request merged**
